"use client";

import { useEffect, useState } from "react";
import { Archive, Boxes, Check, ChevronDown, CircleHelp, Coins, Hammer, MapPinned, PackageOpen, Plus, RotateCcw, Trees, X } from "lucide-react";
import RepublicMap from "@/components/republic-map";
import { accrue, catalog, chooseBranch, claimFinalDecoration, claimParcel, claimTask, combos, completeStep, connected, createTown, currentStep, openParcel, place, slovakDay, steps, store, toggleRoad, type Branch, type DecorationId, type ItemId, type RepublicState } from "@/lib/republic";
import { loadTown, saveTown } from "@/lib/republic-storage";
import "@/app/republic-game.css";

const buildables:ItemId[]=["house","school","library","clinic","park","market","workshop","garden"];
const taskNames={"school-link":"Zapoj školu","green-home":"Ozeleň jeden dom","three-homes":"Zapoj tri domy","care-two":"Ambulancia pre dva domy","market-square":"Tržnica pri námestí","school-pair":"Školská štvrť","craft-pair":"Remeselná štvrť","green-two":"Ozeleň dva domy"} as const;
type Task=keyof typeof taskNames;
export default function RepublicGame(){
 const [town,setTown]=useState<RepublicState|null>(null);const [selected,setSelected]=useState<ItemId|null>(null);const [selectedObject,setSelectedObject]=useState<string|null>(null);const [mode,setMode]=useState<"build"|"roads"|"browse">("browse");const [notice,setNotice]=useState("Pripravujeme tvoju štvrť…");const [storage,setStorage]=useState(true);const [showBuild,setShowBuild]=useState(false);const [showCollection,setShowCollection]=useState(false);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{setTown(loadTown());setNotice("Mesto je uložené v tomto zariadení.");});return()=>cancelAnimationFrame(frame);},[]);
 const commit=(next:RepublicState,message:string)=>{setTown(next);setNotice(message);setStorage(saveTown(next));};
 const apply=(result:ReturnType<typeof place>)=>{if(result.ok)commit(result.state,result.message);else setNotice(result.message);};
 const day=slovakDay();const state=town?accrue(town,day):null;
 useEffect(()=>{if(town&&state&&state.revision!==town.revision){const frame=requestAnimationFrame(()=>{setTown(state);saveTown(state);});return()=>cancelAnimationFrame(frame);}},[day,town,state]);
 const taskCycle:Task[][]=[["school-link","green-home","three-homes"],["school-pair","green-home","three-homes"],["care-two","school-link","green-home"],["market-square","three-homes","school-pair"],["craft-pair","green-two","school-link"],["care-two","market-square","three-homes"],["green-two","school-pair","craft-pair"]];
 if(!state)return <p className="chart-loading" role="status">Pripravujeme Lipovú štvrť…</p>;
 const step=currentStep(state);const dayNumber=Math.floor(Date.UTC(+state.lastDay.slice(0,4),+state.lastDay.slice(5,7)-1,+state.lastDay.slice(8,10))/86400000);const createdNumber=Math.floor(Date.UTC(+state.createdDay.slice(0,4),+state.createdDay.slice(5,7)-1,+state.createdDay.slice(8,10))/86400000);const possibleTasks=taskCycle[Math.max(0,dayNumber-createdNumber)%taskCycle.length];
 const use=(r:ReturnType<typeof place>|ReturnType<typeof openParcel>|ReturnType<typeof claimParcel>|ReturnType<typeof claimFinalDecoration>|ReturnType<typeof chooseBranch>|ReturnType<typeof completeStep>|ReturnType<typeof claimTask>|ReturnType<typeof store>|ReturnType<typeof toggleRoad>)=>apply(r as ReturnType<typeof place>);
 const build=(id:ItemId)=>{setSelected(id);setSelectedObject(null);setMode("build");setShowBuild(false);setNotice(`Vybrané: ${catalog[id].name}. Vyber voľné miesto na mape.`);};
 return <section className="republic">
  <header className="republic-heading"><div><p className="republic-kicker">Nová hra v Herni</p><h1>Malá <span>republika.</span></h1><p>Buduj štvrť, v ktorej sa dá dobre chodiť, bývať aj stretnúť.</p></div><div className="republic-save"><Check size={16}/> {storage?"Uložené v zariadení":"Uloženie sa nepodarilo"}</div></header>
  <div className="republic-topline"><div><b>{state.name}</b><small>Deň {Math.max(1,Math.min(7,steps.length-state.completed.length+1))} · projekt {state.completed.length}/7</small></div><div className="republic-resources"><span><Coins size={16}/> <b>{state.coins}</b> mince</span><span><Boxes size={16}/> <b>{state.materials}</b> materiál</span></div></div>
  <div className="republic-layout"><div className="republic-stage"><RepublicMap town={state} mode={mode} selected={selected} onCell={p=>{if(mode==="roads")use(toggleRoad(state,p));else if(mode==="build"&&selected)use(place(state,selected,p));else setNotice("Vyber stavbu alebo režim cesty.");}} onObject={id=>{const item=state.placed.find(x=>x.instanceId===id);if(item&&!item.fixed){setSelectedObject(id);setNotice(`${catalog[item.id].name}: môžeš ju uložiť a znovu umiestniť.`);}}}/>
   <div className="republic-actions"><button type="button" className={showBuild?"is-active":""} onClick={()=>setShowBuild(x=>!x)}><Hammer size={17}/> Stavať</button><button type="button" className={mode==="roads"?"is-active":""} onClick={()=>{setMode(mode==="roads"?"browse":"roads");setSelected(null);}}><MapPinned size={17}/> Cesty</button><button type="button" className={state.charges?"parcel-ready":""} onClick={()=>use(openParcel(state))}><PackageOpen size={17}/> Zásielka <b>{state.charges}</b></button><button type="button" onClick={()=>setShowCollection(x=>!x)}><Archive size={17}/> Zbierka</button></div>
   {showBuild&&<div className="republic-drawer" aria-label="Stavebný katalóg"><div><b>Vyber stavbu</b><button type="button" aria-label="Zavrieť katalóg" onClick={()=>setShowBuild(false)}><X size={17}/></button></div><div className="republic-build-grid">{(state.finalReward?[...buildables,"culture" as ItemId]:buildables).map(id=>{const inStock=state.inventory.some(x=>x.id===id);const c=catalog[id];return <button type="button" key={id} onClick={()=>build(id)}><span className={`republic-mini icon-${c.icon}`}><Plus size={15}/></span><span><b>{c.name}</b><small>{inStock?"v zásobe":`${c.coins} mincí · ${c.materials} mat.`}</small></span></button>;})}</div></div>}
   {showCollection&&<div className="republic-drawer collection"><div><b>Zbierka ozdôb</b><button type="button" aria-label="Zavrieť zbierku" onClick={()=>setShowCollection(false)}><X size={17}/></button></div>{state.unlocked.length?<div className="republic-collection">{state.unlocked.map(id=><button type="button" key={id} onClick={()=>build(id)}><span className={`republic-mini icon-${catalog[id].icon}`}><Trees size={15}/></span>{catalog[id].name}</button>)}</div>:<p>Otvor prvú zásielku a vyber si ozdobu. Ozdoby môžeš umiestňovať opakovane.</p>}</div>}
   {selectedObject&&state.placed.find(x=>x.instanceId===selectedObject)&&<div className="republic-drawer republic-object-menu"><div><b>{catalog[state.placed.find(x=>x.instanceId===selectedObject)!.id].name}</b><button type="button" aria-label="Zavrieť detail stavby" onClick={()=>setSelectedObject(null)}><X size={17}/></button></div><p>{connected(state,state.placed.find(x=>x.instanceId===selectedObject)!)?"Je napojená na námestie.":"Nie je napojená na cestu z námestia."}</p><button type="button" onClick={()=>{const object=state.placed.find(x=>x.instanceId===selectedObject)!;const id=object.id;use(store(state,object.instanceId));setSelected(id);setSelectedObject(null);setMode("build");}}>Presunúť stavbu</button><button type="button" onClick={()=>{use(store(state,selectedObject));setSelectedObject(null);}}>Uložiť do zásoby</button></div>}
  </div>
  <aside className="republic-side"><article className="republic-project"><p className="republic-kicker">{step?`${step.speaker} · krok ${state.completed.length+1}/7`:"Kapitola dokončená"}</p>{step?<><h2>{step.name}</h2><p>{step.text}</p>{step.id==="discovery"?<div className="republic-branches">{(["museum","market-hall","community-hall"] as Branch[]).map(branch=><button type="button" key={branch} onClick={()=>use(chooseBranch(state,branch))}><b>{{museum:"Múzeum stanice","market-hall":"Tržnica v hale","community-hall":"Komunitná hala"}[branch]}</b><small>{{museum:"Knihy a staré príbehy", "market-hall":"Miesto pre susedov a trhy", "community-hall":"Priestor na stretnutia"}[branch]}</small></button>)}</div>:<><p className={`republic-goal ${step.done(state)?"is-ready":""}`}>{step.done(state)?<><Check size={16}/> Cieľ je pripravený.</>:<><ChevronDown size={16}/> {goalFor(step.id,state)}</>}</p><button type="button" className="republic-complete" disabled={!step.done(state)} onClick={()=>use(completeStep(state))}>{step.id==="opening"?"Otvoriť stanicu":step.id==="preparation"?"Pripraviť halu · 6 / 4":"Potvrdiť krok"}</button></>}</>:<><h2>Stanica znova žije.</h2><p>{state.branch==="museum"?"Stará hala uchováva príbehy štvrte.":state.branch==="market-hall"?"Stará hala sa stala miestom pre trhy.":"Stará hala patrí susedom."}</p><div className="republic-finale"><Check size={18}/> Kapitola je dokončená. Tvoje mesto môže ďalej rásť.</div></>}</article>
   <article className="republic-orders"><div><p className="republic-kicker">Dnešné objednávky</p><small>Každá raz · +2 mince, +1 materiál</small></div>{possibleTasks.map(task=>{const done=state.claimedTasks.includes(`${state.lastDay}:${task}`)||state.claimedTasks.includes(task);return <button type="button" key={task} disabled={done} onClick={()=>use(claimTask(state,task))}><span>{done?<Check size={15}/>:<span className="order-dot"/>}</span><b>{taskNames[task]}</b><small>{done?"vyzdvihnuté":"skontrolovať"}</small></button>})}</article>
   <details className="republic-help"><summary><CircleHelp size={17}/> Ako funguje štvrť</summary><p>Budovy sú zapojené, keď susedia s cestou vedúcou od námestia. Služby dosiahnu k domu na dve políčka. Zásielky sa ukladajú najviac tri dni; vynechaný deň mesto nepoškodí.</p><p>Hra je fiktívna a ukladá sa iba v tomto prehliadači. Účet a cloudové uloženie prídu neskôr.</p><button type="button" onClick={()=>{if(confirm("Začať novú Lipovú štvrť? Súčasný postup sa nahradí iba v tomto zariadení.")){const n=createTown();commit(n,"Začal si novú štvrť.");}}}><RotateCcw size={15}/> Nová štvrť</button></details>
  </aside></div>
  {state.pending&&<div className="republic-modal" role="dialog" aria-modal="true" aria-labelledby="parcel-title"><div className={`republic-parcel rarity-${state.pending.rarity}`}><p className="republic-kicker">{({common:"Bežná",uncommon:"Neobvyklá",rare:"Vzácna",epic:"Epická"}[state.pending.rarity])} zásielka</p><h2 id="parcel-title">Vyber si jeden detail.</h2><p>Nová ozdoba prinesie 8 mincí a 4 materiály. Duplikát sa zmení na 2 materiály.</p><div>{state.pending.cards.map(id=><button type="button" key={id} onClick={()=>use(claimParcel(state,id))}><span className={`parcel-art icon-${catalog[id].icon}`}><Trees size={23}/></span><b>{catalog[id].name}</b><small>{state.unlocked.includes(id)?"už máš · +2 materiály":"nová ozdoba"}</small></button>)}</div></div></div>}
  {!step&&!state.finalReward&&<div className="republic-modal" role="dialog" aria-modal="true" aria-labelledby="final-reward-title"><div className="republic-parcel republic-final-pick rarity-epic"><p className="republic-kicker">Finále kapitoly</p><h2 id="final-reward-title">Vyber si jednu dekoráciu.</h2><p>Táto voľba je tvoja. Môžeš ju potom umiestňovať opakovane.</p><div>{(["bench","flower-bed","linden","fountain","book-kiosk","pergola","clock","bandstand","sculpture","observatory","glasshouse","ceremonial-gate"] as DecorationId[]).map(id=><button type="button" key={id} onClick={()=>use(claimFinalDecoration(state,id))}><span className={`parcel-art icon-${catalog[id].icon}`}><Trees size={23}/></span><b>{catalog[id].name}</b><small>{state.unlocked.includes(id)?"už v zbierke":"finálna dekorácia"}</small></button>)}</div></div></div>}
  <p className="republic-notice" role="status" aria-live="polite">{notice}</p>
 </section>;
}
function goalFor(id:string,s:RepublicState){const c=combos(s);if(id==="school-yard")return"Zapoj školu a park alebo záhradu do dvoch políčok.";if(id==="books")return"Zapoj školu a knižnicu do dvoch políčok.";if(id==="care")return"Ambulancia musí dosiahnuť aspoň na dva zapojené domy.";if(id==="square")return"Zapoj tržnicu najviac dve políčka od námestia.";if(id==="preparation")return `Zapoj stanicu a ${s.branch==="museum"?"knižnicu":s.branch==="market-hall"?"tržnicu":"park alebo záhradu"} do dvoch políčok.`;if(id==="opening")return"Zapoj stanicu, tri domy a vytvor aspoň jednu kombináciu.";return c.school?"Školská štvrť je pripravená.":"Vytvor ďalšie prepojenie v štvrti.";}
