import type { Poll } from "./polls";

export const additionalPolls: Poll[] = [
  {
    "id": "nms-2026-01",
    "agency": "NMS",
    "month": "Január",
    "published": "2026-01-14",
    "start": "2026-01-08",
    "end": "2026-01-11",
    "sample": 1003,
    "source": "https://nms.global/sk/volebny-model-januar-2026-generalka-pred-parlamentnymi-volbami-nas-caka-uz-tento-rok/",
    "sourceName": "NMS Market Research Slovakia",
    "values": {
      "ps": 20.8,
      "smer": 17.8,
      "rep": 12.9,
      "slovensko": 7.2,
      "hlas": 6.5,
      "kdh": 6.4,
      "sas": 6,
      "dem": 5.5,
      "aliancia": 4.6,
      "rodina": 3.2,
      "sns": 2.8,
      "zaludi": 2
    },
    "method": "Online panel (CAWI)",
    "client": "Vlastný výskum NMS",
    "type": "Volebný model",
    "complete": false,
    "note": "Výber hodnôt zo zverejnených kľúčových zistení; nejde o úplnú distribúciu."
  },
  {
    "id": "nms-2026-02",
    "agency": "NMS",
    "month": "Február",
    "published": "2026-02-11",
    "start": "2026-02-04",
    "end": "2026-02-08",
    "sample": 1003,
    "source": "https://nms.global/sk/volebny-model-februar-2026-ako-chybajucich-tisic-hlasov-prekresli-zlozenie-parlamentu/",
    "sourceName": "NMS Market Research Slovakia",
    "values": {
      "ps": 19.1,
      "smer": 17.6,
      "rep": 13.4,
      "slovensko": 7.5,
      "sas": 7.4,
      "hlas": 6.2,
      "dem": 5.7,
      "kdh": 4.9,
      "aliancia": 4,
      "rodina": 3.5,
      "sns": 3,
      "zaludi": 2.3,
      "pnp": 2
    },
    "method": "Online panel (CAWI)",
    "client": "Vlastný výskum NMS",
    "type": "Volebný model",
    "complete": false,
    "note": "Prepísané z číselných hodnôt v kľúčových zisteniach. Slovný komentár zmien môže používať iné zaokrúhlenie. Pri februárovom KDH zdroj uvádza v prehľade 4,9 %, v komentári podrobnejšiu hodnotu 4,95 %."
  },
  {
    "id": "nms-2026-03",
    "agency": "NMS",
    "month": "Marec",
    "published": "2026-03-11",
    "start": "2026-03-04",
    "end": "2026-03-09",
    "sample": 1005,
    "source": "https://nms.global/sk/volebny-model-marec-2026/",
    "sourceName": "NMS Market Research Slovakia",
    "values": {
      "ps": 21.4,
      "smer": 16.7,
      "rep": 13.5,
      "hlas": 7.6,
      "sas": 7.6,
      "slovensko": 7.1,
      "dem": 5.1,
      "kdh": 4.8,
      "aliancia": 4.2,
      "rodina": 3.6,
      "sns": 2.3
    },
    "method": "Online panel (CAWI)",
    "client": "Vlastný výskum NMS",
    "type": "Volebný model",
    "complete": false,
    "note": "Výber hodnôt zo zverejnených kľúčových zistení; nejde o úplnú distribúciu."
  },
  {
    "id": "nms-2026-04",
    "agency": "NMS",
    "month": "Apríl",
    "published": "2026-04-15",
    "start": "2026-04-08",
    "end": "2026-04-13",
    "sample": 1001,
    "source": "https://nms.global/sk/volebny-model-april-2026/",
    "sourceName": "NMS Market Research Slovakia",
    "values": {
      "ps": 20.2,
      "smer": 17.3,
      "rep": 13.6,
      "sas": 7.3,
      "slovensko": 7.1,
      "hlas": 7,
      "dem": 5.8,
      "kdh": 5.3,
      "aliancia": 4.2,
      "rodina": 3.8,
      "sns": 2.8,
      "zaludi": 2.3
    },
    "method": "Online panel (CAWI)",
    "client": "Vlastný výskum NMS",
    "type": "Volebný model",
    "complete": false,
    "note": "Výber hodnôt zo zverejnených kľúčových zistení; nejde o úplnú distribúciu."
  },
  {
    "id": "ako-2026-01",
    "agency": "AKO",
    "month": "Január",
    "published": "2026-01-26",
    "start": "2026-01-13",
    "end": "2026-01-20",
    "sample": 1000,
    "source": "https://ako.sk/wp-content/uploads/2026/01/ag.AKO_VOLEBNE-PREF-JANUAR-2026-tlacova-sprava-FINAL.pdf",
    "sourceName": "AKO · pôvodná správa",
    "values": {
      "ps": 23.2,
      "smer": 16.9,
      "hlas": 9.2,
      "slovensko": 8,
      "sas": 7.5,
      "rep": 7.2,
      "kdh": 7,
      "dem": 6.3,
      "sns": 4.7,
      "aliancia": 4.3,
      "pnp": 2.6,
      "rodina": 2.3
    },
    "method": "Telefonické dopytovanie",
    "client": "JOJ 24",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Percentá z rozhodnutých voličov (62,4 % celej vzorky). Niektoré menšie subjekty nie sú prepísané."
  },
  {
    "id": "ako-2026-02",
    "agency": "AKO",
    "month": "Február",
    "published": "2026-02-20",
    "start": "2026-02-10",
    "end": "2026-02-19",
    "sample": 1000,
    "source": "https://ako.sk/wp-content/uploads/2026/03/ag.AKO_VOLEBNE-PREF-FEBRUAR-2026-tlacova-sprava_.pdf",
    "sourceName": "AKO · pôvodná správa",
    "values": {
      "ps": 20.6,
      "smer": 16.4,
      "slovensko": 9.3,
      "hlas": 8.8,
      "rep": 8.7,
      "sas": 7.9,
      "kdh": 7.4,
      "dem": 6.2,
      "sns": 4.8,
      "aliancia": 4.6,
      "rodina": 2.9,
      "pnp": 2.2
    },
    "method": "Telefonické dopytovanie",
    "client": "JOJ 24",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Percentá z rozhodnutých voličov (70,2 % celej vzorky). Niektoré menšie subjekty nie sú prepísané."
  },
  {
    "id": "ako-2026-03",
    "agency": "AKO",
    "month": "Marec",
    "published": "2026-03-19",
    "start": "2026-03-10",
    "end": "2026-03-18",
    "sample": 1000,
    "source": "https://ako.sk/wp-content/uploads/2026/03/ag.AKO_VOLEBNE-PREF-MAREC-2026-tlacova-sprava.pdf",
    "sourceName": "AKO · pôvodná správa",
    "values": {
      "ps": 20.1,
      "smer": 17.1,
      "hlas": 8.7,
      "slovensko": 8.6,
      "rep": 8.6,
      "sas": 7.7,
      "kdh": 7.2,
      "dem": 5.8,
      "sns": 4.8,
      "aliancia": 4.1,
      "rodina": 3.9,
      "pnp": 2.3,
      "zaludi": 0.3
    },
    "method": "Telefonické dopytovanie",
    "client": "JOJ 24",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Percentá z rozhodnutých voličov (63,7 % celej vzorky). Niektoré menšie subjekty nie sú prepísané."
  },
  {
    "id": "ako-2026-04",
    "agency": "AKO",
    "month": "Apríl",
    "published": "2026-04-21",
    "start": "2026-04-08",
    "end": "2026-04-17",
    "sample": 1000,
    "source": "https://ako.sk/wp-content/uploads/2026/04/ag.AKO_VOLEBNE-PREF-APRIL-2026-tlacova-sprava-MUSTRA.pdf",
    "sourceName": "AKO · pôvodná správa",
    "values": {
      "ps": 20.8,
      "smer": 17.8,
      "hlas": 8.9,
      "sas": 8.2,
      "rep": 8,
      "slovensko": 7.7,
      "kdh": 7.6,
      "dem": 6,
      "sns": 4.9,
      "aliancia": 4.7,
      "rodina": 2.8,
      "pnp": 2.2
    },
    "method": "Telefonické dopytovanie",
    "client": "JOJ 24",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Percentá z rozhodnutých voličov (69 % celej vzorky). Niektoré menšie subjekty nie sú prepísané."
  },
  {
    "id": "ipsos-2026-01",
    "agency": "IPSOS",
    "month": "Január",
    "published": "2026-01-23",
    "start": "2026-01-15",
    "end": "2026-01-20",
    "sample": 1034,
    "source": "https://www.ipsos.com/sites/default/files/ct/news/documents/2026-01/IPSOS%20-%20Tla%C4%8Dov%C3%A1%20spr%C3%A1va%20-%20Reprezentat%C3%ADvny%20prieskum%20politick%C3%BDch%20preferenci%C3%AD%2023.%201.%202026.pdf",
    "sourceName": "IPSOS · pôvodná správa",
    "values": {
      "ps": 20.5,
      "smer": 17.6,
      "rep": 12.3,
      "sas": 8.4,
      "slovensko": 8.3,
      "hlas": 7.3,
      "kdh": 6.8,
      "dem": 5.2,
      "aliancia": 3.5,
      "rodina": 2.4,
      "sns": 2.4,
      "pnp": 1.7,
      "zaludi": 1.1
    },
    "method": "Online zber (CAWI)",
    "client": "Denník N",
    "type": "Volebný model",
    "complete": false,
    "note": "Model váži ochotu ísť voliť. Kategória „iné strany“ je uvedená oddelene.",
    "other": 2.6
  },
  {
    "id": "ipsos-2026-02",
    "agency": "IPSOS",
    "month": "Február",
    "published": "2026-02-23",
    "start": "2026-02-16",
    "end": "2026-02-20",
    "sample": 1037,
    "source": "https://www.ipsos.com/sites/default/files/ct/news/documents/2026-02/IPSOS%20-%20Tla%C4%8Dov%C3%A1%20spr%C3%A1va%20-%20Reprezentat%C3%ADvny%20prieskum%20politick%C3%BDch%20preferenci%C3%AD%2023.%202.%202026.pdf",
    "sourceName": "IPSOS · pôvodná správa",
    "values": {
      "ps": 18.8,
      "smer": 18.4,
      "rep": 11.7,
      "slovensko": 8.8,
      "sas": 8.4,
      "hlas": 7.4,
      "dem": 6.2,
      "kdh": 6,
      "aliancia": 4.7,
      "sns": 2.8,
      "rodina": 2.5,
      "pnp": 1.3,
      "zaludi": 1.1
    },
    "method": "Online zber (CAWI)",
    "client": "Denník N",
    "type": "Volebný model",
    "complete": false,
    "note": "Model váži ochotu ísť voliť. Kategória „iné strany“ je uvedená oddelene.",
    "other": 2
  },
  {
    "id": "ipsos-2026-03",
    "agency": "IPSOS",
    "month": "Marec",
    "published": "2026-03-23",
    "start": "2026-03-16",
    "end": "2026-03-19",
    "sample": 1008,
    "source": "https://www.ipsos.com/sites/default/files/ct/news/documents/2026-03/IPSOS%20-%20Tla%C4%8Dov%C3%A1%20spr%C3%A1va%20-%20Reprezentat%C3%ADvny%20prieskum%20politick%C3%BDch%20preferenci%C3%AD%2023.%203.%202026.pdf",
    "sourceName": "IPSOS · pôvodná správa",
    "values": {
      "ps": 20.6,
      "smer": 20,
      "rep": 11.3,
      "hlas": 8.2,
      "slovensko": 7.9,
      "sas": 7.2,
      "kdh": 6.3,
      "dem": 6,
      "aliancia": 4.3,
      "sns": 2.4,
      "rodina": 2.2,
      "zaludi": 1.1
    },
    "method": "Online zber (CAWI)",
    "client": "Denník N",
    "type": "Volebný model",
    "complete": false,
    "note": "Model váži ochotu ísť voliť. Kategória „iné strany“ je uvedená oddelene.",
    "other": 2.5
  },
  {
    "id": "ipsos-2026-05",
    "agency": "IPSOS",
    "month": "Máj",
    "published": null,
    "start": "2026-05-15",
    "end": "2026-05-20",
    "sample": null,
    "source": "https://www.ipsos.com/sites/default/files/ct/news/documents/2026-07/IPSOS%20-%20Tla%C4%8Dov%C3%A1%20spr%C3%A1va%20-%20Reprezentat%C3%ADvny%20prieskum%20politick%C3%BDch%20preferenci%C3%AD%2025.8.2026.pdf",
    "sourceName": "IPSOS · pôvodná správa",
    "values": {
      "ps": 19.7,
      "smer": 19.1,
      "rep": 11.2,
      "slovensko": 7.8,
      "hlas": 8.3,
      "sas": 8.2,
      "kdh": 5.9,
      "dem": 4.7,
      "aliancia": 3.2,
      "pnp": 1.5,
      "sns": 2.7,
      "rodina": 3.1,
      "zaludi": 2.5,
      "lsns": 1
    },
    "method": "Online zber (CAWI)",
    "client": "Denník N",
    "type": "Volebný model",
    "complete": false,
    "note": "Hodnoty a obdobie zberu sú z historického stĺpca augustovej správy IPSOS. Veľkosť pôvodnej vzorky a deň prvého publikovania v tomto zdroji nie sú uvedené.",
    "other": 1
  },
  {
    "id": "ipsos-2026-06",
    "agency": "IPSOS",
    "month": "Jún",
    "published": null,
    "start": "2026-06-17",
    "end": "2026-06-23",
    "sample": null,
    "source": "https://www.ipsos.com/sites/default/files/ct/news/documents/2026-07/IPSOS%20-%20Tla%C4%8Dov%C3%A1%20spr%C3%A1va%20-%20Reprezentat%C3%ADvny%20prieskum%20politick%C3%BDch%20preferenci%C3%AD%2025.8.2026.pdf",
    "sourceName": "IPSOS · pôvodná správa",
    "values": {
      "ps": 20.2,
      "smer": 19,
      "rep": 10,
      "slovensko": 7.3,
      "hlas": 6.8,
      "sas": 8.8,
      "kdh": 6.5,
      "dem": 5.1,
      "aliancia": 4.7,
      "pnp": 2.3,
      "sns": 3.4,
      "rodina": 2.8,
      "zaludi": 1.2
    },
    "method": "Online zber (CAWI)",
    "client": "Denník N",
    "type": "Volebný model",
    "complete": false,
    "note": "Hodnoty a obdobie zberu sú z historického stĺpca augustovej správy IPSOS. Veľkosť pôvodnej vzorky a deň prvého publikovania v tomto zdroji nie sú uvedené.",
    "other": 1.7
  },
  {
    "id": "ipsos-2026-08",
    "agency": "IPSOS",
    "month": "August",
    "published": "2026-08-25",
    "start": "2026-08-18",
    "end": "2026-08-23",
    "sample": 1061,
    "source": "https://www.ipsos.com/sites/default/files/ct/news/documents/2026-07/IPSOS%20-%20Tla%C4%8Dov%C3%A1%20spr%C3%A1va%20-%20Reprezentat%C3%ADvny%20prieskum%20politick%C3%BDch%20preferenci%C3%AD%2025.8.2026.pdf",
    "sourceName": "IPSOS · pôvodná správa",
    "values": {
      "ps": 18.1,
      "smer": 17.9,
      "rep": 10.9,
      "slovensko": 8.4,
      "hlas": 8.2,
      "sas": 8.2,
      "kdh": 7.3,
      "dem": 4.7,
      "aliancia": 3.4,
      "pnp": 3.1,
      "sns": 3,
      "rodina": 2.8,
      "zaludi": 1.8
    },
    "method": "Online zber (CAWI)",
    "client": "Denník N",
    "type": "Volebný model",
    "complete": false,
    "note": "Model váži ochotu ísť voliť. Kategória „iné strany“ je uvedená oddelene.",
    "other": 2.1
  },
  {
    "id": "focus-2026-02",
    "agency": "FOCUS",
    "month": "Február",
    "published": "2026-02-12",
    "start": "2026-02-03",
    "end": "2026-02-09",
    "sample": 1014,
    "source": "https://www.focus-research.sk/wp-content/uploads/2026/02/Volebne-preferencie-politickych-stran_februar_2026.pdf",
    "sourceName": "FOCUS · pôvodná správa",
    "values": {
      "ps": 19.3,
      "smer": 17.7,
      "rep": 9.9,
      "slovensko": 9.7,
      "hlas": 8.1,
      "sas": 7.6,
      "kdh": 6.9,
      "dem": 5.6,
      "aliancia": 4.7,
      "sns": 4.1,
      "rodina": 2.3,
      "pnp": 1.9,
      "zaludi": 0.8,
      "ku": 0.5
    },
    "method": "Osobné a online rozhovory",
    "client": "360tka.sk",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Percentá z rozhodnutých respondentov (69,2 % vzorky). Tento podiel nie je odhadom volebnej účasti. Dátum publikovania je dátum tlačovej správy.",
    "other": 0.9
  },
  {
    "id": "focus-2026-03",
    "agency": "FOCUS",
    "month": "Marec",
    "published": "2026-04-02",
    "start": "2026-03-20",
    "end": "2026-03-27",
    "sample": 1038,
    "source": "https://www.focus-research.sk/wp-content/uploads/2026/04/Volebne-preferencie-politickych-stran_marec_2026.pdf",
    "sourceName": "FOCUS · pôvodná správa",
    "values": {
      "ps": 19.1,
      "smer": 17.1,
      "rep": 10.6,
      "slovensko": 8.5,
      "hlas": 8.2,
      "sas": 7.1,
      "kdh": 6.4,
      "dem": 5.4,
      "sns": 4.4,
      "aliancia": 3.9,
      "rodina": 3.6,
      "pnp": 2.1,
      "zaludi": 1,
      "vidiek": 0.6,
      "ku": 0.2
    },
    "method": "Osobné a online rozhovory",
    "client": "360tka.sk",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Percentá z rozhodnutých respondentov (73,6 % vzorky). Tento podiel nie je odhadom volebnej účasti. Dátum publikovania je dátum tlačovej správy.",
    "other": 1.8
  },
  {
    "id": "focus-2026-05",
    "agency": "FOCUS",
    "month": "Máj",
    "published": "2026-05-14",
    "start": "2026-05-05",
    "end": "2026-05-11",
    "sample": 1017,
    "source": "https://www.focus-research.sk/wp-content/uploads/2026/05/Volebne-preferencie-politickych-stran_maj_2026.pdf",
    "sourceName": "FOCUS · pôvodná správa",
    "values": {
      "ps": 18.3,
      "smer": 18.1,
      "rep": 9.7,
      "slovensko": 9.6,
      "hlas": 8.4,
      "kdh": 7.5,
      "sas": 7.2,
      "dem": 5.2,
      "sns": 4.5,
      "aliancia": 3.8,
      "rodina": 3.1,
      "pnp": 2,
      "zaludi": 0.9,
      "vidiek": 0.4,
      "ku": 0.4
    },
    "method": "Osobné a online rozhovory",
    "client": "360tka.sk",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Percentá z rozhodnutých respondentov (70,9 % vzorky). Tento podiel nie je odhadom volebnej účasti. Dátum publikovania je dátum tlačovej správy.",
    "other": 0.9
  },
  {
    "id": "focus-2026-06",
    "agency": "FOCUS",
    "month": "Jún",
    "published": "2026-07-03",
    "start": "2026-06-22",
    "end": "2026-06-29",
    "sample": 1027,
    "source": "https://www.focus-research.sk/wp-content/uploads/2026/07/Volebne-preferencie-politickych-stran_jun_2026.pdf",
    "sourceName": "FOCUS · pôvodná správa",
    "values": {
      "ps": 18.1,
      "smer": 17.7,
      "rep": 11.6,
      "slovensko": 9,
      "hlas": 8,
      "sas": 7,
      "kdh": 6.7,
      "dem": 4.8,
      "sns": 4.2,
      "aliancia": 3.9,
      "rodina": 2.8,
      "pnp": 2.7,
      "zaludi": 1.6,
      "vidiek": 0.4,
      "ku": 0.1
    },
    "method": "Osobné a online rozhovory",
    "client": "360tka.sk",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Percentá z rozhodnutých respondentov (73,3 % vzorky). Tento podiel nie je odhadom volebnej účasti. Dátum publikovania je dátum tlačovej správy.",
    "other": 1.4
  },
  {
    "id": "focus-2026-09",
    "agency": "FOCUS",
    "month": "September",
    "published": "2026-09-10",
    "start": "2026-09-01",
    "end": "2026-09-07",
    "sample": 1012,
    "source": "https://www.focus-research.sk/wp-content/uploads/2026/09/Volebne-preferencie-politickych-stran_sept_2026.pdf",
    "sourceName": "FOCUS · pôvodná správa",
    "values": {
      "ps": 17.3,
      "smer": 17.3,
      "rep": 12.4,
      "slovensko": 8.9,
      "hlas": 8.4,
      "sas": 7.5,
      "kdh": 6.4,
      "dem": 5,
      "sns": 4,
      "aliancia": 3.8,
      "rodina": 3.2,
      "pnp": 2.8,
      "zaludi": 1.6,
      "vidiek": 0.6,
      "ku": 0.4
    },
    "method": "Osobné a online rozhovory",
    "client": "360tka.sk",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Percentá z rozhodnutých respondentov (74,4 % vzorky). Tento podiel nie je odhadom volebnej účasti. Dátum publikovania je dátum tlačovej správy.",
    "other": 0.4
  },
  {
    "id": "infostat-2026-01",
    "agency": "INFOSTAT",
    "month": "Január",
    "published": null,
    "start": "2026-01-12",
    "end": "2026-01-16",
    "sample": 1085,
    "source": "https://www.infostat.sk/csv/suhrnna-sprava/pdf/Volebne-preferencie-januar-porov-2026.pdf",
    "sourceName": "INFOSTAT · Centrum sociálnych výskumov",
    "values": {
      "ps": 22.2,
      "smer": 17.5,
      "rep": 11.6,
      "hlas": 9.9,
      "kdh": 8.8,
      "sas": 6.2,
      "slovensko": 5.2,
      "dem": 4.1,
      "aliancia": 3.5,
      "sns": 2.7,
      "rodina": 2.1
    },
    "method": "Osobné rozhovory (PAPI)",
    "client": "Vlastný výskum CSV pri INFOSTAT-e",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Deň prvého zverejnenia nie je v pôvodnom dokumente jednoznačne uvedený. Dátum vytvorenia PDF nepovažujeme za dátum publikovania. Zdroj obsahuje výber strán; chýbajúce podiely neodhadujeme."
  },
  {
    "id": "infostat-2026-03",
    "agency": "INFOSTAT",
    "month": "Marec",
    "published": null,
    "start": "2026-03-09",
    "end": "2026-03-13",
    "sample": 1159,
    "source": "https://www.infostat.sk/csv/suhrnna-sprava/pdf/Volebne-preferencie-marec-2026.pdf",
    "sourceName": "INFOSTAT · Centrum sociálnych výskumov",
    "values": {
      "ps": 21.1,
      "smer": 20.2,
      "rep": 9.7,
      "kdh": 9.4,
      "hlas": 8.3,
      "sas": 7,
      "dem": 5.5,
      "slovensko": 4,
      "aliancia": 3.8,
      "sns": 3.3,
      "rodina": 1.4,
      "pnp": 1
    },
    "method": "Osobné rozhovory (PAPI)",
    "client": "Vlastný výskum CSV pri INFOSTAT-e",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Deň prvého zverejnenia nie je v pôvodnom dokumente jednoznačne uvedený. Dátum vytvorenia PDF nepovažujeme za dátum publikovania. Zdroj obsahuje výber strán; chýbajúce podiely neodhadujeme."
  },
  {
    "id": "infostat-2026-05",
    "agency": "INFOSTAT",
    "month": "Máj",
    "published": null,
    "start": "2026-05-11",
    "end": "2026-05-15",
    "sample": 1003,
    "source": "https://www.infostat.sk/csv/suhrnna-sprava/pdf/NAZORY_2_2026.pdf",
    "sourceName": "INFOSTAT · Centrum sociálnych výskumov",
    "values": {
      "ps": 22.2,
      "smer": 18.4,
      "rep": 9.8,
      "hlas": 9,
      "kdh": 8.9,
      "slovensko": 7.6,
      "sas": 7.3,
      "dem": 4.3,
      "aliancia": 3.5,
      "sns": 2.5,
      "rodina": 1.8,
      "pnp": 1.1,
      "lsns": 0.7
    },
    "method": "Osobné rozhovory (CAPI)",
    "client": "Vlastný výskum CSV pri INFOSTAT-e",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Deň prvého zverejnenia nie je v pôvodnom dokumente jednoznačne uvedený. Dátum vytvorenia PDF nepovažujeme za dátum publikovania. Zdroj obsahuje výber strán; chýbajúce podiely neodhadujeme. NÁZORY 2/2026, strany 87–89 (PDF 88–90); základ otázky N = 564, celá vzorka n = 1 003."
  },
  {
    "id": "infostat-2026-06",
    "agency": "INFOSTAT",
    "month": "Jún",
    "published": null,
    "start": "2026-06-01",
    "end": "2026-06-05",
    "sample": 1020,
    "source": "https://www.infostat.sk/csv/suhrnna-sprava/pdf/Volebne_preferencie_jun_2026.pdf",
    "sourceName": "INFOSTAT · Centrum sociálnych výskumov",
    "values": {
      "smer": 19.8,
      "ps": 18.6,
      "kdh": 9.9,
      "hlas": 9.4,
      "rep": 8.7,
      "sas": 8.1,
      "slovensko": 6.9,
      "dem": 4.5,
      "aliancia": 4.1,
      "rodina": 3.5,
      "sns": 2.8,
      "lsns": 2,
      "pnp": 1.5
    },
    "method": "Osobné rozhovory (CAPI)",
    "client": "Vlastný výskum CSV pri INFOSTAT-e",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Deň prvého zverejnenia nie je v pôvodnom dokumente jednoznačne uvedený. Dátum vytvorenia PDF nepovažujeme za dátum publikovania. Zdroj obsahuje výber strán; chýbajúce podiely neodhadujeme."
  },
  {
    "id": "infostat-2026-07",
    "agency": "INFOSTAT",
    "month": "Júl",
    "published": null,
    "start": "2026-07-13",
    "end": "2026-07-17",
    "sample": 1049,
    "source": "https://www.infostat.sk/csv/suhrnna-sprava/pdf/Volebne_preferencie_jul_2026.pdf",
    "sourceName": "INFOSTAT · Centrum sociálnych výskumov",
    "values": {
      "ps": 19.2,
      "smer": 18.8,
      "hlas": 8.5,
      "slovensko": 8.5,
      "sas": 8.2,
      "kdh": 8,
      "dem": 7,
      "rep": 6.7,
      "aliancia": 5.4,
      "sns": 3.8,
      "rodina": 3.1,
      "pnp": 1.5
    },
    "method": "Osobné rozhovory (CAPI)",
    "client": "Vlastný výskum CSV pri INFOSTAT-e",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Deň prvého zverejnenia nie je v pôvodnom dokumente jednoznačne uvedený. Dátum vytvorenia PDF nepovažujeme za dátum publikovania. Zdroj obsahuje výber strán; chýbajúce podiely neodhadujeme."
  },
  {
    "id": "infostat-2026-08",
    "agency": "INFOSTAT",
    "month": "August",
    "published": null,
    "start": "2026-08-03",
    "end": "2026-08-07",
    "sample": 1046,
    "source": "https://www.infostat.sk/csv/suhrnna-sprava/pdf/Volebne_preferencie_august_2026.pdf",
    "sourceName": "INFOSTAT · Centrum sociálnych výskumov",
    "values": {
      "smer": 20.4,
      "ps": 18.6,
      "sas": 9.8,
      "hlas": 8.9,
      "rep": 8.1,
      "kdh": 7.9,
      "slovensko": 6.6,
      "dem": 6,
      "aliancia": 5.8,
      "sns": 2.9,
      "rodina": 2.2,
      "pnp": 1.9
    },
    "method": "Osobné rozhovory (CAPI)",
    "client": "Vlastný výskum CSV pri INFOSTAT-e",
    "type": "Volebné preferencie",
    "complete": false,
    "note": "Deň prvého zverejnenia nie je v pôvodnom dokumente jednoznačne uvedený. Dátum vytvorenia PDF nepovažujeme za dátum publikovania. Zdroj obsahuje výber strán; chýbajúce podiely neodhadujeme."
  }
];
