export type PoliticalNews = {id:string;published:string;category:'Parlament'|'Vláda'|'Prieskumy';title:string;summary:string;sourceName:string;source:string};
// Redakčný výber. Bez automatického zberu a bez nároku na úplné pokrytie; každá správa má pôvodný zdroj.
export const newsChecked='2026-09-14';
export const politicalNews:PoliticalNews[]=[
  {id:'pellegrini-sprava-14',published:'2026-09-14',category:'Parlament',title:'Prezident žiada vystúpenie v pléne so správou o stave republiky',summary:'Peter Pellegrini požiadal Národnú radu o možnosť predniesť správu o stave Slovenskej republiky. Podľa TN Live chce bilancovať s dôrazom na budúcoročný rozpočet a dokument Vízia Slovensko 2040. Termín vystúpenia zatiaľ určený nie je.',sourceName:'TN Live',source:'https://tnlive.sk/domace/clanok/1051131-prezident-poziadal-o-vystupenie-v-plene-so-spravou-o-stave-republiky'},
  {id:'koalicna-rada-14',published:'2026-09-14',category:'Vláda',title:'Koaličná rada sa dohodla na postupe pred septembrovou schôdzou',summary:'Úrad vlády uviedol, že koaličná rada sa bez rozporov dohodla na otvorení schôdze aj na spoločnom postupe. Rokovanie sa začína v utorok 15. septembra a má takmer 300 bodov. Predseda parlamentu Richard Raši pripúšťa, že potrvá dlhšie ako plánované štyri týždne.',sourceName:'TASR / Teraz.sk',source:'https://www.teraz.sk/slovensko/koalicna-rada-sa-dohodla-na-otvoreni/992228-clanok.html'},
  {id:'sutaj-estok-taraba-14',published:'2026-09-14',category:'Vláda',title:'Šutaj Eštok očakáva návrh na odvolanie Tarabu v utorok',summary:'Predseda Hlasu uviedol, že premiér verejne signalizoval podanie návrhu 15. septembra. Dodal, že by Tomášovi Tarabovi a Andrejovi Dankovi želal dohodu. Ide o očakávanie člena koalície, nie o potvrdené podanie návrhu.',sourceName:'Denník N · Minúta po minúte',source:'https://dennikn.sk/minuta/5560980'},
  {id:'danko-taraba-13',published:'2026-09-13',category:'Parlament',title:'Danko chce rokovanie o odvolaní Tarabu už vo štvrtok',summary:'Predseda SNS navrhuje, aby parlament o odvolaní ministra životného prostredia rokoval vo štvrtok. Podľa Denníka N má premiér doručiť návrh prezidentovi do utorka. Ak by nový minister nebol vymenovaný súčasne, rezort by dočasne viedol Robert Fico.',sourceName:'Denník N · Minúta po minúte',source:'https://dennikn.sk/minuta/5558798'},
  {id:'taraba-demisia-13',published:'2026-09-13',category:'Vláda',title:'Taraba: sám demisiu nepodám',summary:'Minister životného prostredia odmietol, že by podal demisiu, a uviedol, že ho o odvolaní nikto nekontaktoval. Podľa jeho slov mu výsledky práce nedovoľujú abdikovať. Správa nadväzuje na piatkové vyjadrenie premiéra o termíne 30. septembra.',sourceName:'Denník N · Minúta po minúte',source:'https://dennikn.sk/minuta/5558001'},
  {id:'taraba-fico-12',published:'2026-09-12',category:'Vláda',title:'Fico: Taraba odstúpi, ak sa vzťahy so SNS do 30. septembra neurovnajú',summary:'Premiér po rokovaniach uviedol, že je nešťastný z vývoja vzťahu medzi ministrom životného prostredia a SNS. Podľa dohody urobí Taraba politické gesto a odstúpi z vlády, ak sa vzťahy do 30. septembra neurovnajú.',sourceName:'TASR / Teraz.sk',source:'https://www.teraz.sk/slovensko/premier-som-nestastny-z-vyvoja-vz/991828-clanok.html'},
  {id:'fpu-september',published:'2026-09-11',category:'Vláda',title:'Nadácia upozorňuje na spornú dotáciu z FPU',summary:'Nadácia Zastavme korupciu opísala vrátenie festivalovej žiadosti do hodnotenia napriek možnému konfliktu záujmov. Dotknutý člen rady uviedol, že sa účinkovania vzdal; festival neštandardný postup odmieta.',sourceName:'Nadácia Zastavme korupciu',source:'https://zastavmekorupciu.sk/kauzy/olha-pomohol-ziskat-dotaciu-projektu-v-konflikte-zaujmov/'},
  {id:'taraba-september',published:'2026-09-11',category:'Vláda',title:'Michelko avizuje návrh na odvolanie Tarabu',summary:'Podľa predsedu klubu SNS Romana Michelka má premiér podať návrh do 15. septembra. STVR informuje o avizovanom kroku; správa nepotvrdzuje, že minister už bol odvolaný.',sourceName:'STVR',source:'https://spravy.stvr.sk/spravy-po-minute/navrh-na-odvolanie-tomasa-tarabu-nom-sns-z-postu-podpredsedu-vlady-a-ministra-zivotneho-prostredia-poda-premier-do-15-septembra/'},
  {id:'parliament-september',published:'2026-09-11',category:'Parlament',title:'Poslancov čaká návrat do parlamentu a takmer 300 bodov',summary:'Jesenná schôdza sa má začať 15. septembra. Podľa STVR sú na programe aj pravidlá sociálnych sietí pre deti, nový Občiansky zákonník a úprava voľby zo zahraničia.',sourceName:'STVR',source:'https://spravy.stvr.sk/spravy-po-minute/poslanci-narodnej-rady-sr-sa-v-utorok-15-septembra-vratia-po-letnej-prestavke-do-lavic/'},
  {id:'focus-september',published:'2026-09-10',category:'Prieskumy',title:'Septembrový Focus: Smer a PS zhodne na 17,3 %',summary:'Agentúra Focus merala od 1. do 7. septembra na vzorke 1 012 respondentov. Smer-SD aj Progresívne Slovensko by získali 17,3 %, za nimi Republika s 12,4 %. Do parlamentu by sa podľa merania dostalo osem strán.',sourceName:'STVR',source:'https://spravy.stvr.sk/2026/09/novy-prieskum-focusu-smer-sd-a-ps-by-ziskali-rovnaky-pocet-hlasov-do-parlamentu-by-sa-dostalo-osem-stran'},
  {id:'nms-september',published:'2026-09-10',category:'Prieskumy',title:'NMS zverejnila septembrový volebný model',summary:'Septembrové meranie vzniklo z dát zbieraných od 2. do 7. septembra. Pôvodný článok obsahuje výsledky a metodiku; meranie je aj medzi vstupmi Modelu Mandát.',sourceName:'NMS Market Research Slovakia',source:'https://nms.global/sk/volebny-model-september-2026/'},
  {id:'f16-september',published:'2026-09-10',category:'Vláda',title:'Opozícia kritizuje nákup štyroch stíhačiek F-16',summary:'Nákup za približne 390 miliónov eur označili poslanci PS a SaS za zbytočný luxus. Minister obrany Robert Kaliňák tvrdí, že lietadlá sú potrebné a je rozumnejšie kúpiť ich teraz. Splácať sa majú do roku 2030.',sourceName:'STVR',source:'https://spravy.stvr.sk/2026/09/opozicia-kritizuje-nakup-styroch-novych-stihaciek-f-16-hovori-o-zbytocnom-luxuse-podla-ministra-kalinaka-ich-potrebujeme'},
  {id:'kuffa-september',published:'2026-09-10',category:'Vláda',title:'SNS presadzuje Kuffu, prezident má výhrady',summary:'Podľa Denníka N sľúbil premiér SNS, že návrh na odvolanie Tomáša Tarabu pošle do 15. septembra. Strana presadzuje na jeho miesto štátneho tajomníka Filipa Kuffu, ktorého Peter Pellegrini spochybnil. Taraba má ešte zastupovať Slovensko na Valnom zhromaždení OSN.',sourceName:'Denník N',source:'https://dennikn.sk/5553294/fico-do-utorka-odvola-tarabu-sns-sa-pripravila-aj-na-obstrukciu-prezidenta/'},
  {id:'v4-september',published:'2026-09-10',category:'Vláda',title:'V4 rokovala v Bratislave o rozpočte EÚ a energiách',summary:'Robert Fico po stretnutí premiérov V4 a Írska zdôraznil poľnohospodársku politiku a koordináciu pred rokovaniami EÚ. Znižovanie cien elektriny označil za tému ďalšej spolupráce.',sourceName:'STVR / TASR',source:'https://spravy.stvr.sk/2026/09/premier-robert-fico-veri-ze-klucovou-temou-krajin-v4-bude-znizovanie-cien-elektriny/'},
  {id:'lex-para-september',published:'2026-09-10',category:'Parlament',title:'PS navrhuje obmedziť súbeh obhajoby a poradenstva vláde',summary:'Návrh má riešiť možný konflikt záujmov advokátov pôsobiacich ako vládni poradcovia. Predseda advokátskej komory ho odmieta ako protiústavný; PS pripúšťa úpravy. Zatiaľ ide o návrh zákona.',sourceName:'STVR',source:'https://spravy.stvr.sk/2026/09/opozicia-navrhuje-lex-para-advokati-by-podla-ps-nemohli-radit-vlade-a-zaroven-obhajovat-obvinenych-z-korupcie/'},
  {id:'sns-blokovanie-09',published:'2026-09-09',category:'Parlament',title:'SNS nebude blokovať otvorenie septembrovej schôdze',summary:'Poslanecký klub SNS oznámil, že rokovanie od 15. septembra blokovať nebude. Strana očakáva, že premiér v ten deň doručí písomný návrh na odvolanie ministra životného prostredia. Informáciu potvrdil štátny tajomník Filip Kuffa.',sourceName:'TN Live',source:'https://tnlive.sk/domace/clanok/1050189-sns-ustupuje-od-blokovania-parlamentu-ocakavaju-ze-premier-doruci-prezidentovi-navrh-na-odvolanie-ministra-tarabu'},
  {id:'border-september',published:'2026-09-09',category:'Vláda',title:'Cvičenie na českej hranici neznamená zavedenie kontrol',summary:'Slovenské a české bezpečnostné zložky preverovali postupy pri možnom obnovení hraničných kontrol. Minister Matúš Šutaj Eštok uviedol, že ich zavedenie v najbližšom období neočakáva.',sourceName:'STVR / TASR',source:'https://spravy.stvr.sk/spravy-po-minute/k-zavedeniu-kontrol-na-hranici-s-ceskom-v-najblizsom-obdobi-nedojde-potvrdil-minister-sutaj-estok/'}
];

/**
 * „Posledných 7 dní“ je pohyblivé okno vrátane dneška, nie kalendárny týždeň:
 * v pondelok by kalendárny týždeň ukázal iba dnešok a prehľad by pôsobil prázdno.
 * Budúce dátumy sa nezobrazujú nikdy, ani v celom výbere.
 */
export function filterNews(items:PoliticalNews[],today:string,period:string,category:string){
  const from=new Date(new Date(today+'T12:00:00Z').getTime()-6*86400000).toISOString().slice(0,10);
  return items.filter(n=>n.published<=today&&(category==='all'||n.category===category)&&(period==='all'||(period==='today'?n.published===today:n.published>=from))).sort((a,b)=>b.published.localeCompare(a.published)||a.id.localeCompare(b.id));
}
