export type PoliticalNews = {id:string;published:string;category:'Parlament'|'Vláda'|'Prieskumy';title:string;summary:string;sourceName:string;source:string};
// Editorial test selection. No automated ingestion or claim of continuous coverage.
export const newsChecked='2026-09-13';
export const politicalNews:PoliticalNews[]=[
  {id:'fpu-september',published:'2026-09-11',category:'Vláda',title:'Nadácia upozorňuje na spornú dotáciu z FPU',summary:'Nadácia Zastavme korupciu opísala vrátenie festivalovej žiadosti do hodnotenia napriek možnému konfliktu záujmov. Dotknutý člen rady uviedol, že sa účinkovania vzdal; festival neštandardný postup odmieta.',sourceName:'Nadácia Zastavme korupciu',source:'https://zastavmekorupciu.sk/kauzy/olha-pomohol-ziskat-dotaciu-projektu-v-konflikte-zaujmov/'},
  {id:'v4-september',published:'2026-09-10',category:'Vláda',title:'V4 rokovala v Bratislave o rozpočte EÚ a energiách',summary:'Robert Fico po stretnutí premiérov V4 a Írska zdôraznil poľnohospodársku politiku a koordináciu pred rokovaniami EÚ. Znižovanie cien elektriny označil za tému ďalšej spolupráce.',sourceName:'STVR / TASR',source:'https://spravy.stvr.sk/2026/09/premier-robert-fico-veri-ze-klucovou-temou-krajin-v4-bude-znizovanie-cien-elektriny/'},
  {id:'lex-para-september',published:'2026-09-10',category:'Parlament',title:'PS navrhuje obmedziť súbeh obhajoby a poradenstva vláde',summary:'Návrh má riešiť možný konflikt záujmov advokátov pôsobiacich ako vládni poradcovia. Predseda advokátskej komory ho odmieta ako protiústavný; PS pripúšťa úpravy. Zatiaľ ide o návrh zákona.',sourceName:'STVR',source:'https://spravy.stvr.sk/2026/09/opozicia-navrhuje-lex-para-advokati-by-podla-ps-nemohli-radit-vlade-a-zaroven-obhajovat-obvinenych-z-korupcie/'},
  {id:'border-september',published:'2026-09-09',category:'Vláda',title:'Cvičenie na českej hranici neznamená zavedenie kontrol',summary:'Slovenské a české bezpečnostné zložky preverovali postupy pri možnom obnovení hraničných kontrol. Minister Matúš Šutaj Eštok uviedol, že ich zavedenie v najbližšom období neočakáva.',sourceName:'STVR / TASR',source:'https://spravy.stvr.sk/spravy-po-minute/k-zavedeniu-kontrol-na-hranici-s-ceskom-v-najblizsom-obdobi-nedojde-potvrdil-minister-sutaj-estok/'},
  {id:'taraba-september',published:'2026-09-11',category:'Vláda',title:'Michelko avizuje návrh na odvolanie Tarabu',summary:'Podľa predsedu klubu SNS Romana Michelka má premiér podať návrh do 15. septembra. STVR informuje o avizovanom kroku; správa nepotvrdzuje, že minister už bol odvolaný.',sourceName:'STVR',source:'https://spravy.stvr.sk/spravy-po-minute/navrh-na-odvolanie-tomasa-tarabu-nom-sns-z-postu-podpredsedu-vlady-a-ministra-zivotneho-prostredia-poda-premier-do-15-septembra/'},
  {id:'parliament-september',published:'2026-09-11',category:'Parlament',title:'Poslancov čaká návrat do parlamentu a takmer 300 bodov',summary:'Jesenná schôdza sa má začať 15. septembra. Podľa STVR sú na programe aj pravidlá sociálnych sietí pre deti, nový Občiansky zákonník a úprava voľby zo zahraničia.',sourceName:'STVR',source:'https://spravy.stvr.sk/spravy-po-minute/poslanci-narodnej-rady-sr-sa-v-utorok-15-septembra-vratia-po-letnej-prestavke-do-lavic/'},
  {id:'taraba-fico-12',published:'2026-09-12',category:'Vláda',title:'Fico: Taraba odstúpi, ak sa vzťahy so SNS do 30. septembra neurovnajú',summary:'Premiér po rokovaniach uviedol, že je nešťastný z vývoja vzťahu medzi ministrom životného prostredia a SNS. Podľa dohody urobí Taraba politické gesto a odstúpi z vlády, ak sa vzťahy do 30. septembra neurovnajú.',sourceName:'TASR / Teraz.sk',source:'https://www.teraz.sk/slovensko/premier-som-nestastny-z-vyvoja-vz/991828-clanok.html'},
  {id:'taraba-demisia-13',published:'2026-09-13',category:'Vláda',title:'Taraba: sám demisiu nepodám',summary:'Minister životného prostredia odmietol, že by podal demisiu, a uviedol, že ho o odvolaní nikto nekontaktoval. Podľa jeho slov mu výsledky práce nedovoľujú abdikovať. Správa nadväzuje na piatkové vyjadrenie premiéra o termíne 30. septembra.',sourceName:'Denník N · Minúta po minúte',source:'https://dennikn.sk/minuta/5558001'},
  {id:'nms-september',published:'2026-09-10',category:'Prieskumy',title:'NMS zverejnila septembrový volebný model',summary:'Septembrové meranie vzniklo z dát zbieraných od 2. do 7. septembra. Pôvodný článok obsahuje výsledky a metodiku; meranie je aj medzi vstupmi Modelu Mandát.',sourceName:'NMS Market Research Slovakia',source:'https://nms.global/sk/volebny-model-september-2026/'}
];

export function filterNews(items:PoliticalNews[],today:string,period:string,category:string){
  const now=new Date(today+'T12:00:00Z');
  const monday=new Date(now.getTime()-((now.getUTCDay()+6)%7)*86400000).toISOString().slice(0,10);
  return items.filter(n=>n.published<=today&&(category==='all'||n.category===category)&&(period==='all'||(period==='today'?n.published===today:n.published>=monday))).sort((a,b)=>b.published.localeCompare(a.published)||a.id.localeCompare(b.id));
}
