export type PoliticalNews = {id:string;published:string;category:'Parlament'|'Vláda'|'Prieskumy';title:string;summary:string;detail:string[];sourceName:string;source:string};
/*
  Redakčný výber. Bez automatického zberu a bez nároku na úplné pokrytie.
  `summary` je krátky popis do zoznamu, `detail` je naše dlhšie zhrnutie pôvodného článku,
  ktoré otvára titulok. Zo zoznamov sme odkazy na cudzie weby odstránili, aby čitateľ
  neodchádzal skôr, než dostane obsah; vydavateľ aj odkaz na originál sú v detaile,
  lebo zhrnutie stojí na jeho práci.
*/
export const newsChecked='2026-09-19';
export const politicalNews:PoliticalNews[]=[
  {id:'schodza-start-15',published:'2026-09-15',category:'Parlament',title:'Jesenná schôdza sa začala, poslanci majú vyše 300 bodov',
   summary:'Národná rada sa po letnej prestávke vrátila k rokovaniu. Na programe je vyše 300 bodov vrátane ústavných zmien, nového Občianskeho zákonníka a regulácie sociálnych sietí; transakčná daň medzi nimi nie je.',
   detail:['Národná rada otvorila v utorok 15. septembra jesennú schôdzu, prvú po letnej prestávke. Na programe má vyše 300 bodov, čo je nezvyčajne veľa aj preto, že vyše sto návrhov poslanci presunuli z júnovej schôdze. Predseda parlamentu Richard Raši (Hlas-SD) povedal, že koalícia sa na programe dohodla a so schválením nečaká problém.',
     'Medzi citlivými témami sú viaceré ústavné zmeny — návrh ministerstva spravodlivosti umožniť rozpustenie parlamentu referendom a návrh Hlasu skrátiť volebné obdobie rovnakou cestou. V druhom čítaní je nový Občiansky zákonník, ministerstvo školstva prinieslo systém prevencie radikalizácie vrátane obmedzenia sociálnych sietí pre deti do 16 rokov a Smer návrh na nové pravidlá hlasovania zo zahraničia, ktoré sa má rozšíriť aj na prezidentské voľby.',
     'O transakčnej dani sa na schôdzi nerokuje; koalícia ju odsunula na rokovania koaličnej rady. Počas schôdze má so správou o stave republiky vystúpiť aj prezident Peter Pellegrini.'],
   sourceName:'ta3',source:'https://www.ta3.com/clanok/1071361/viac-nez-300-bodov-a-niekolko-citlivych-tem-pozrite-si-co-vsetko-caka-poslancov-po-navrate-do-parlamentu'},
  {id:'taraba-navrh-15',published:'2026-09-15',category:'Vláda',title:'Fico podal návrh na odvolanie Tarabu, prezident rozhodne po návrate z USA',
   summary:'Premiér doručil prezidentovi návrh na odvolanie ministra životného prostredia. Pellegrini uviedol, že sa ním bude zaoberať po návrate z pracovnej cesty v USA a až potom určí ďalší postup.',
   detail:['Premiér Robert Fico v utorok 15. septembra doručil prezidentovi Petrovi Pellegrinimu návrh na odvolanie ministra životného prostredia Tomáša Tarabu. Termín vyplynul z májovej dohody Fica, Tarabu a predsedu SNS Andreja Danka: ak sa minister so stranou nezmieri, jeho pôsobenie sa skončí do konca septembra.',
     'Prezidentská kancelária uviedla, že hlava štátu sa odvolaním bude zaoberať po návrate zo zahraničnej pracovnej cesty v Spojených štátoch, kde je na Valnom zhromaždení OSN, a až potom stanoví termín ďalšieho postupu. Pellegrini sa teda nezaviazal Tarabu odvolať obratom.',
     'Podľa informácií z koalície by rezort dočasne prevzal priamo premiér a o nástupcovi sa má rokovať až po 30. septembri. SNS má pripraveného jediného kandidáta — štátneho tajomníka Filipa Kuffu, ku ktorému sa prezident už skôr vyjadril, že na Slovensku sú aj kvalitnejší ľudia.'],
   sourceName:'TASR / Teraz.sk',source:'https://www.teraz.sk/slovensko/prezident-sa-dorucenym-navrhom-na-odv/992356-clanok.html'},
  {id:'vojaci-nato-17',published:'2026-09-17',category:'Parlament',title:'Poslanci schválili vyslanie vojakov na východné krídlo NATO, za bola aj opozícia',
   summary:'Parlament odobril vyslanie až 101 vojakov do Poľska a Rumunska v rámci operácie Východná stráž. Za hlasovalo 129 poslancov naprieč koalíciou aj opozíciou; predseda SNS Danko bol proti.',
   detail:['Národná rada vo štvrtok 17. septembra schválila vyslanie až 101 slovenských vojakov na posilnenie protivzdušnej obrany východného krídla NATO, predovšetkým do Poľska a Rumunska. Ide o operáciu Východná stráž, ktorá reaguje na prieniky dronov nad územie spojencov.',
     'Návrh získal širokú podporu: za hlasovalo 129 zo 140 prítomných poslancov, jeden bol proti a desiati sa zdržali. Okrem Smeru a Hlasu ho podporili aj opozičné PS, SaS, KDH a Slovensko. Proti hlasoval predseda SNS Andrej Danko, väčšina poslancov jeho strany sa zdržala.',
     'Minister obrany Robert Kaliňák (Smer-SD) uviedol, že vojaci budú sledovať vzdušný priestor a identifikovať dronové hrozby aj s pomocou nových 3D radarov, ktoré si tak otestujú v reálnej operácii. Hlasovanie prišlo deň pred vyjadreniami premiéra spochybňujúcimi článok 5 Severoatlantickej zmluvy.'],
   sourceName:'Noviny.sk',source:'https://www.noviny.sk/slovensko/1260338-poslanci-schvalili-vyslanie-vojakov-na-vychodne-kridlo-nato-za-hlasovala-aj-opozicia'},
  {id:'ustava-referendum-17',published:'2026-09-17',category:'Parlament',title:'Ústavná zmena o skrátení volebného obdobia referendom prešla do druhého čítania',
   summary:'Návrh Hlasu, aby sa volebné obdobie parlamentu dalo skrátiť platným referendom, podporilo 78 zo 136 prítomných poslancov. Na konečné schválenie ústavnej zmeny treba 90 hlasov.',
   detail:['Poslanci vo štvrtok 17. septembra posunuli do druhého čítania ústavný návrh Hlasu-SD, podľa ktorého by sa volebné obdobie Národnej rady dalo skrátiť platným referendom. Návrh podporilo 78 zo 136 prítomných poslancov; na konečné schválenie ústavného zákona je potrebná ústavná väčšina 90 hlasov, ktorú koalícia sama nemá.',
     'Do druhého čítania prešla aj súvisiaca novela volebného zákona. Podpredseda Republiky Milan Uhrík neskôr uviedol, že ak by jeho strana bola v parlamente, myšlienku by podporila, hoci by ešte doladila technické detaily proti zneužitiu.',
     'V ten istý deň poslanci posunuli ďalej aj zvýšenie príspevku pri narodení dieťaťa z 829,86 eura na 1 000 eur pri prvom až štvrtom dieťati a zo 157,37 eura na 200 eur pri piatom a ďalšom, s účinnosťou od 1. januára 2027.'],
   sourceName:'TASR / Teraz.sk',source:'https://www.teraz.sk/slovensko/suhrn-parlamentom-odhlasovanych-navrh/993081-clanok.html'},
  {id:'fico-clanok5-18',published:'2026-09-18',category:'Vláda',title:'Fico spochybnil článok 5: nechce, aby Slovensko bolo vo vojne „kvôli nejakému článku 5“',
   summary:'Premiér vyhlásil, že si neželá účasť Slovenska vo vojnovom konflikte kvôli článku 5 Severoatlantickej zmluvy, a varoval pred celoeurópskym konfliktom. Zároveň dodal, že Slovensko je v NATO a záväzky mu záležia.',
   detail:['Premiér Robert Fico pri návšteve Prešova vo štvrtok 17. septembra povedal, že situácia nikdy nebola taká vážna, pokiaľ ide o možnosť celoeurópskeho vojnového konfliktu, a že podľa neho budeme svedkami veľkých vojenských operácií na Ukrajine. Doplnil vetu, ktorá vyvolala najväčšiu odozvu: neželá si, aby bolo Slovensko súčasťou nejakého vojnového konfliktu kvôli nejakému článku 5.',
     'Zároveň uviedol, že Slovensko je v NATO, váži si spoluprácu a záleží mu na plnení záväzkov, no ako predseda vlády urobí všetko preto, aby krajina nebola zatiahnutá do vojnového konfliktu. Článok 5 Severoatlantickej zmluvy je pritom jadrom kolektívnej obrany: útok na jedného člena sa považuje za útok na všetkých.',
     'Vyjadrenie zaznamenali aj zahraničné médiá. Bruselské Politico napísalo, že premiér spochybnil záväzok kolektívnej obrany, reportér Wall Street Journal Jaroslav Trofimov sa ironicky spýtal, či sú slovenskí vojaci v Pobaltí pre čerstvý vzduch.'],
   sourceName:'STVR',source:'https://spravy.stvr.sk/2026/09/premier-fico-spochybnuje-clanok-5-severoatlantickej-zmluvy-obava-sa-celoeuropskeho-vojnoveho-konfliktu'},
  {id:'reakcie-clanok5-18',published:'2026-09-18',category:'Vláda',title:'Na premiérove slová o článku 5 reagovali prezident, Čaputová aj opozícia',
   summary:'Pellegrini vyhlásil, že Slovensko nemôže a nechce byť pasívnym členom NATO. Čaputová uviedla, že nikto zodpovedný by nemal spochybňovať záväzky v aliancii. Šimečka označil premiéra za bezpečnostné riziko, KDH žiada vysvetlenie v parlamente.',
   detail:['Deň po premiérových slovách o článku 5 vystúpil na vojenskom cintoríne Háj Nicovô prezident Peter Pellegrini. Povedal, že Slovensko nemôže a nechce byť pasívnym členom NATO, ale aktívnym prispievateľom do systému kolektívnej bezpečnosti, a že záväzok brániť vlasť nie je ani trochu formálny. Pripomenul hrozby ako drony, hybridné vedenie vojny, kybernetické útoky a dezinformácie, ktoré podľa neho už dávno nie sú hypotetické.',
     'Bývalá prezidentka Zuzana Čaputová uviedla, že nikto zodpovedný by nemal spochybňovať naše záväzky v aliancii, pretože sú zároveň bezpečnostnou garanciou; odstrašenie podľa nej stojí na dôveryhodnosti kolektívnej obrany. Predseda PS Michal Šimečka označil premiéra za bezpečnostné riziko pre Slovensko s tým, že spochybnením princípu kolektívnej obrany nám spravil hanbu a škodu.',
     'Podpredseda KDH Viliam Karas vyhlásil, že článok 5 je základným pilierom bezpečnosti Slovenska a takéto výroky nepatria do úst predsedu vlády; hnutie žiada vysvetlenie v parlamente. Kriticky sa ozvali aj Juraj Krúpa (SaS) a Tomáš Valášek (PS).'],
   sourceName:'Denník N · Minúta po minúte',source:'https://dennikn.sk/minuta/5571159'},
  {id:'fico-ukrajina-18',published:'2026-09-18',category:'Vláda',title:'Fico pre chorobu zrušil cestu na Ukrajinu, samit prijal deklaráciu bez neho',
   summary:'Premiér deň po vyjadreniach o článku 5 zrušil účasť na prvom samite Karpatskej osmičky. Slovensko zastúpil štátny tajomník Marek Eštok; osem krajín prijalo deklaráciu o Karpatskej integračnej iniciatíve.',
   detail:['Premiér Robert Fico v piatok 18. septembra zrušil pre chorobu plánovanú cestu na Ukrajinu, kde sa v Bukovli začal prvý samit Karpatskej osmičky. Slovensko na trojdňovom podujatí zastúpil štátny tajomník ministerstva zahraničných vecí Marek Eštok.',
     'Nová regionálna platforma spája osem krajín karpatského regiónu — Slovensko, Ukrajinu, Poľsko, Česko, Maďarsko, Rakúsko, Rumunsko a Srbsko; jej vznik oznámil ukrajinský prezident Volodymyr Zelenskyj. Maďarsko nebolo zastúpené na vysokej politickej úrovni.',
     'Účastníci prijali záverečnú deklaráciu o Karpatskej integračnej iniciatíve. Týka sa energetickej odolnosti, spoločných dopravných projektov, ochrany biodiverzity Karpát, cestovného ruchu aj podpory kreatívneho priemyslu; podľa dokumentu môže iniciatíva pomôcť postupnej integrácii kandidátskych krajín do Európskej únie.'],
   sourceName:'TASR / Teraz.sk',source:'https://www.teraz.sk/slovensko/na-karpatskom-summite-prijali-deklaraci/993382-clanok.html'},
  {id:'okte-menovania-18',published:'2026-09-18',category:'Vláda',title:'Do vedenia štátnej firmy OKTE prišli ľudia napojení na koalíciu',
   summary:'Denník N opísal menovania v stopercentne štátnej spoločnosti OKTE pod ministerstvom financií: Kamil Peteraj ml. s odmenou vyše 15-tisíc eur mesačne, šéfka kancelárie predsedu SNS aj manžel europoslankyne Smeru.',
   detail:['Denník N v piatok 18. septembra opísal personálne zmeny v spoločnosti OKTE, ktorá je stopercentne štátna a patrí pod ministerstvo financií vedené podpredsedom Smeru Ladislavom Kamenickým. Do vedenia sa dostali ľudia napojení na koaličné strany.',
     'Podľa denníka je medzi nimi Kamil Peteraj mladší s mesačnou odmenou vyše 15-tisíc eur, ktorý v roku 2024 zarobil vyše 175-tisíc eur; predtým viedol kanceláriu ministerky kultúry Ľubice Laššákovej. Ďalej Zuzana Škopcová, riaditeľka kancelárie predsedu SNS, a manžel europoslankyne Smeru Judity Laššákovej.',
     'Denník upozorňuje, že ročné odmeny vedenia presahujú ročný zisk spoločnosti. Ide o zistenia redakcie; vyjadrenia dotknutých osôb ani ministerstva k jednotlivým menovaniam zatiaľ nemáme overené z druhého zdroja.'],
   sourceName:'Denník N',source:'https://dennikn.sk/5567448/'},
  {id:'taraba-spalovna-18',published:'2026-09-18',category:'Vláda',title:'Taraba definitívne zastavil spaľovňu pri Dudinciach',
   summary:'Minister životného prostredia v odvolacom konaní zrušil projekt spaľovne pri kúpeľných Dudinciach. Argumentoval tým, že takéto zariadenia patria do priemyselných zón a kapacita 130-tisíc ton ročne bola pre okres neprimeraná.',
   detail:['Minister životného prostredia Tomáš Taraba v piatok 18. septembra oznámil, že v odvolacom konaní definitívne zastavil projekt spaľovne odpadu pri Dudinciach. Rozhodnutie prišlo tri dni po tom, čo premiér podal návrh na jeho odvolanie z funkcie.',
     'Minister argumentoval, že spaľovne patria do priemyselných zón a areálov bývalých chemických závodov, nie do kúpeľných miest. Plánovaná kapacita 130-tisíc ton odpadu ročne podľa neho nedávala zmysel, keďže okres Krupina vyprodukuje len zlomok tohto množstva.',
     'Zároveň uviedol, že Slovensko moderné zariadenia na energetické využitie odpadu potrebuje, lebo po roku 2035 sa v Európe skládkovanie takmer skončí a bez vlastných kapacít by krajina závisela od susedov. Spor je teda o umiestnenie, nie o samotnú technológiu.'],
   sourceName:'Denník N · Minúta po minúte',source:'https://dennikn.sk/minuta/5570586'},
  {id:'pellegrini-sprava-14',published:'2026-09-14',category:'Parlament',title:'Prezident žiada vystúpenie v pléne so správou o stave republiky',
   summary:'Peter Pellegrini požiadal Národnú radu o možnosť predniesť správu o stave Slovenskej republiky. Chce bilancovať s dôrazom na budúcoročný rozpočet a dokument Vízia Slovensko 2040. Termín vystúpenia zatiaľ určený nie je.',
   detail:['Prezident Peter Pellegrini v pondelok 14. septembra požiadal Národnú radu o možnosť vystúpiť v pléne so správou o stave Slovenskej republiky. Ide o jeho ústavné právo; konkrétny termín vystúpenia zatiaľ určený nie je.',
     'Podľa TN Live chce prezident bilancovať svoje doterajšie pôsobenie s dôrazom na budúcoročný štátny rozpočet a na strategický dokument Vízia Slovensko 2040.',
     'Žiadosť prišla deň pred otvorením jesennej schôdze parlamentu, ktorá sa začína v utorok 15. septembra popoludní.'],
   sourceName:'TN Live',source:'https://tnlive.sk/domace/clanok/1051131-prezident-poziadal-o-vystupenie-v-plene-so-spravou-o-stave-republiky'},
  {id:'koalicna-rada-14',published:'2026-09-14',category:'Vláda',title:'Koaličná rada sa dohodla na postupe pred septembrovou schôdzou',
   summary:'Úrad vlády uviedol, že koaličná rada sa bez rozporov dohodla na otvorení schôdze aj na spoločnom postupe. Rokovanie sa začína v utorok 15. septembra a má takmer 300 bodov.',
   detail:['Koaličná rada sa v pondelok 14. septembra zišla na Úrade vlády. Podľa úradu sa strany bez akýchkoľvek rozporov dohodli na otvorení septembrovej schôdze aj na spoločnom postupe počas nej.',
     'Schôdza sa začína v utorok 15. septembra popoludní a má takmer 300 bodov. Predseda parlamentu Richard Raši (Hlas-SD) pripustil, že vzhľadom na počet návrhov môže trvať dlhšie ako plánované štyri týždne.',
     'Dohoda o otvorení je podstatná preto, že SNS ešte začiatkom septembra zvažovala blokovanie schôdze pre spor o ministra životného prostredia.'],
   sourceName:'TASR / Teraz.sk',source:'https://www.teraz.sk/slovensko/koalicna-rada-sa-dohodla-na-otvoreni/992228-clanok.html'},
  {id:'sutaj-estok-taraba-14',published:'2026-09-14',category:'Vláda',title:'Šutaj Eštok očakáva návrh na odvolanie Tarabu v utorok',
   summary:'Predseda Hlasu uviedol, že premiér verejne signalizoval podanie návrhu 15. septembra. Ide o očakávanie člena koalície, nie o potvrdené podanie návrhu.',
   detail:['Predseda Hlasu a minister vnútra Matúš Šutaj Eštok v pondelok 14. septembra povedal, že očakáva podanie návrhu na odvolanie ministra životného prostredia Tomáša Tarabu v utorok. Podľa jeho slov premiér aj verejne signalizoval, že návrh dá 15. septembra.',
     'Zároveň dodal, že by Tarabovi a predsedovi SNS Andrejovi Dankovi želal, aby našli spoločnú reč, a že premiérovi jeho situáciu nezávidí. Spomenul tiež, že Hlas si zadefinoval priority pre rozpočtové rokovania vrátane pomoci rodinám a dostavby nemocníc.',
     'Ide o očakávanie koaličného partnera, nie o potvrdené podanie návrhu. Návrh na odvolanie ministra podáva premiér a rozhoduje o ňom prezident.'],
   sourceName:'Denník N · Minúta po minúte',source:'https://dennikn.sk/minuta/5560980'},
  {id:'danko-taraba-13',published:'2026-09-13',category:'Parlament',title:'Danko chce rokovanie o odvolaní Tarabu už vo štvrtok',
   summary:'Predseda SNS navrhuje, aby parlament o odvolaní ministra životného prostredia rokoval vo štvrtok. Premiér má podľa Denníka N doručiť návrh prezidentovi do utorka.',
   detail:['Predseda SNS Andrej Danko v nedeľu 13. septembra navrhol, aby parlament o odvolaní ministra životného prostredia Tomáša Tarabu rokoval už vo štvrtok. Premiér má podľa Denníka N doručiť návrh prezidentovi do utorka.',
     'Danko chce týmto postupom demonštrovať vážnosť svojho návrhu voči prezidentovi aj voči samotnému Tarabovi.',
     'Stretnutie Roberta Fica s kandidátom SNS Filipom Kuffom bolo naplánované na stredu. Ak by Kuffa nebol vymenovaný súčasne s Tarabovým odvolaním, rezort by dočasne viedol sám premiér; poverenie ministerky kultúry Martiny Šimkovičovej Danko odmietol s tým, že má svoje spektrum a záber.'],
   sourceName:'Denník N · Minúta po minúte',source:'https://dennikn.sk/minuta/5558798'},
  {id:'taraba-demisia-13',published:'2026-09-13',category:'Vláda',title:'Taraba: sám demisiu nepodám',
   summary:'Minister životného prostredia odmietol, že by podal demisiu, a uviedol, že ho o odvolaní nikto nekontaktoval. Podľa jeho slov mu výsledky práce nedovoľujú abdikovať.',
   detail:['Minister životného prostredia Tomáš Taraba v nedeľu 13. septembra v relácii Joj 24 vyhlásil, že sám demisiu nepodá. Uviedol, že ho ohľadom odvolania nikto nekontaktoval a že má v kalendári naplánované rokovania aj po 15. septembri.',
     'Argumentoval výsledkami svojej práce slovami, že mu nedovoľujú podať abdikáciu. SNS podľa neho kope do vlastných radov.',
     'Vysvetlil tiež, že prihlášku do SNS si podal preto, aby sa strana mohla hlásiť k výsledkom jeho rezortu. Vyjadrenie nadväzuje na piatkové slová premiéra o termíne 30. septembra.'],
   sourceName:'Denník N · Minúta po minúte',source:'https://dennikn.sk/minuta/5558001'},
  {id:'taraba-fico-12',published:'2026-09-12',category:'Vláda',title:'Fico: Taraba odstúpi, ak sa vzťahy so SNS do 30. septembra neurovnajú',
   summary:'Premiér uviedol, že je nešťastný z vývoja vzťahu medzi ministrom životného prostredia a SNS. Podľa dohody urobí Taraba politické gesto a odstúpi, ak sa vzťahy do konca septembra neurovnajú.',
   detail:['Premiér Robert Fico v piatok 12. septembra uviedol, že je nešťastný z vývoja vzťahu medzi ministrom životného prostredia a SNS. Konflikt sa podľa neho nielenže neutlmuje, ale hrotí sa do extrému, a preto sa do jeho riešenia vložil.',
     'Podľa dohody, ktorú premiér opísal, urobí Tomáš Taraba politické gesto a odstúpi z vlády, ak sa vzťahy do 30. septembra neurovnajú. Dôvodom je strata dôvery nominujúcej strany; SNS má podľa koaličnej zmluvy právo vymeniť svojho ministra.',
     'SNS Tarabovi vyčíta, že si úspechy pripisuje sebe a neúspechy strane, a že nemá vecnú diskusiu o materiáloch z rezortu, napríklad o zonácii, veterných parkoch či batériových úložiskách. Ako náhradu navrhuje štátneho tajomníka Filipa Kuffu, pri ktorom prezident žiada kvalitnejšiu nomináciu.',
     'Taraba tvrdí, že skončiť sa nechystá a že je jediný minister, ktorého chcú odvolať za dobre vykonanú prácu.'],
   sourceName:'TASR / Teraz.sk',source:'https://www.teraz.sk/slovensko/premier-som-nestastny-z-vyvoja-vz/991828-clanok.html'},
  {id:'fpu-september',published:'2026-09-11',category:'Vláda',title:'Nadácia upozorňuje na spornú dotáciu z Fondu na podporu umenia',
   summary:'Nadácia Zastavme korupciu opísala vrátenie festivalovej žiadosti do hodnotenia napriek možnému konfliktu záujmov. Dotknutý člen rady sa účinkovania vzdal; festival neštandardný postup odmieta.',
   detail:['Nadácia Zastavme korupciu opísala prípad dotácie pre festival Musica Nobilis v jeho 28. ročníku. Žiadosť o takmer 36 000 eur zamestnanec Fondu na podporu umenia pôvodne vyradil pre konflikt záujmov, pretože v programe mal účinkovať člen rady fondu Ľubomír Richter. Rada napokon projekt podporila sumou 20 000 eur.',
     'Podľa nadácie požiadal o vrátenie žiadosti do hodnotenia Matúš Oľha, člen rady od roku 2024, ktorý bol v roku 2025 krátko jej predsedom a z tejto funkcie odstúpil po kauze odpočúvacej techniky. Zákon hovorí, že člen rady ani jemu blízka osoba nemôžu byť v priamom realizačnom vzťahu k projektu.',
     'Richter sa písomne vzdal honorára a neskôr z projektu úplne odstúpil. Festival uviedol, že žiadosť podal klasickým spôsobom a neštandardný postup odmieta; fond na otázky nadácie podľa článku nereagoval.',
     'Väzba na stranu neznamená vinu strany. Rezort kultúry vedie nominantka SNS, článok však netvrdí, že členovia rady fondu sú členmi tejto strany.'],
   sourceName:'Nadácia Zastavme korupciu',source:'https://zastavmekorupciu.sk/kauzy/olha-pomohol-ziskat-dotaciu-projektu-v-konflikte-zaujmov/'},
  {id:'taraba-september',published:'2026-09-11',category:'Vláda',title:'Michelko avizuje návrh na odvolanie Tarabu',
   summary:'Podľa predsedu klubu SNS Romana Michelka má premiér podať návrh do 15. septembra. Ide o avizovaný krok, nie o potvrdené odvolanie ministra.',
   detail:['Predseda poslaneckého klubu SNS Roman Michelko 11. septembra uviedol, že premiér podá návrh na odvolanie Tomáša Tarabu z postu podpredsedu vlády a ministra životného prostredia do 15. septembra.',
     'Taraba na to reagoval tvrdením, že je prvým ministrom, ktorého chcú odvolať za vysokú úroveň výkonu funkcie.',
     'Správa informuje o avizovanom kroku. Nepotvrdzuje, že minister už bol odvolaný; návrh podáva premiér a rozhoduje o ňom prezident.'],
   sourceName:'STVR',source:'https://spravy.stvr.sk/spravy-po-minute/navrh-na-odvolanie-tomasa-tarabu-nom-sns-z-postu-podpredsedu-vlady-a-ministra-zivotneho-prostredia-poda-premier-do-15-septembra/'},
  {id:'parliament-september',published:'2026-09-11',category:'Parlament',title:'Poslancov čaká návrat do parlamentu a takmer 300 bodov',
   summary:'Jesenná schôdza sa má začať 15. septembra. Na programe sú pravidlá sociálnych sietí pre deti, nový Občiansky zákonník aj úprava voľby zo zahraničia.',
   detail:['Jesenná schôdza Národnej rady sa má začať v utorok 15. septembra popoludní a na programe má takmer 300 bodov.',
     'Z vládnych návrhov sú v hre nový Občiansky zákonník v druhom čítaní, regulácia sociálnych sietí pre deti do 16 rokov v rámci zákona o ochrane pred radikalizáciou, novela stavebného zákona, novela zákona o DPH pre platformové hospodárstvo, nový zákon o energetickej efektívnosti a novela zákona o prídavku na dieťa.',
     'Koaličné strany prinášajú novelu volebného zákona so zmenou hlasovania zo zahraničia (Smer-SD), zvýšenie dôchodkov po 90. roku veku a Deň štátnej vlajky (SNS) či ústavnú novelu o skrátení volebného obdobia referendom (Hlas-SD). Opozícia navrhuje dvanásťmesačné ochranné obdobie pred voľbami (PS), zákon proti papalášizmu (Hnutie Slovensko), zmeny v Trestnom zákone (SaS) a starostlivosť špecialistov pre dospelých od 15 rokov (KDH).',
     'Na programe sú aj vetované zákony a návrhy na vyslovenie nedôvery siedmim ministrom.'],
   sourceName:'STVR',source:'https://spravy.stvr.sk/spravy-po-minute/poslanci-narodnej-rady-sr-sa-v-utorok-15-septembra-vratia-po-letnej-prestavke-do-lavic/'},
  {id:'focus-september',published:'2026-09-10',category:'Prieskumy',title:'Septembrový Focus: Smer a PS zhodne na 17,3 %',
   summary:'Agentúra merala od 1. do 7. septembra na vzorke 1 012 respondentov. Smer-SD aj Progresívne Slovensko by získali 17,3 %, za nimi Republika s 12,4 %.',
   detail:['Agentúra Focus merala od 1. do 7. septembra na vzorke 1 012 respondentov. Smer-SD aj Progresívne Slovensko by získali zhodne 17,3 % hlasov.',
     'Za nimi skončila Republika s 12,4 %, Hnutie Slovensko s 8,9 %, Hlas-SD s 8,4 %, SaS so 7,5 %, KDH so 6,4 % a Demokrati s 5,0 %. Do parlamentu by sa podľa merania dostalo osem strán.',
     'Ide o volebný model agentúry, nie o predpoveď výsledku volieb. Meranie je jedným z piatich vstupov, z ktorých počítame Model Mandát.'],
   sourceName:'STVR',source:'https://spravy.stvr.sk/2026/09/novy-prieskum-focusu-smer-sd-a-ps-by-ziskali-rovnaky-pocet-hlasov-do-parlamentu-by-sa-dostalo-osem-stran'},
  {id:'nms-september',published:'2026-09-10',category:'Prieskumy',title:'NMS zverejnila septembrový volebný model',
   summary:'Meranie vzniklo z dát zbieraných od 2. do 7. septembra na vzorke 1 004 respondentov. Progresívne Slovensko by získalo 21,6 %, Smer-SD 16,2 % a Republika 15,6 %.',
   detail:['NMS Market Research Slovakia zverejnila septembrový volebný model. Dáta zbierala online od 2. do 7. septembra na vzorke 1 004 respondentov, s viacrozmerným vážením podľa pohlavia, veku, kraja, vzdelania, národnosti a voľby v roku 2023.',
     'Progresívne Slovensko by získalo 21,6 % (rast o 2,4 percentuálneho bodu), Smer-SD 16,2 %, Republika 15,6 % (rast o 2,4 bodu), Hnutie Slovensko 9,0 %, SaS 6,8 %, Hlas-SD 6,4 % a KDH 5,8 %. Deklarovaná účasť bola 61 %.',
     'Agentúra uvádza, že prieskum robila na vlastné náklady bez zadávateľa. Meranie je jedným zo vstupov Modelu Mandát.'],
   sourceName:'NMS Market Research Slovakia',source:'https://nms.global/sk/volebny-model-september-2026/'},
  {id:'f16-september',published:'2026-09-10',category:'Vláda',title:'Opozícia kritizuje nákup štyroch stíhačiek F-16',
   summary:'Nákup za približne 390 miliónov eur označili poslanci PS a SaS za zbytočný luxus. Minister obrany Robert Kaliňák tvrdí, že lietadlá sú potrebné.',
   detail:['Opozičné strany kritizovali nákup štyroch ďalších stíhačiek F-16 za približne 390 miliónov eur. Poslanec PS Tomáš Valášek hovoril o hazarde s obranou Slovenska a o rozhadzovaní, poslanec SaS Juraj Krúpa označil nákup za zbytočný, keďže Slovensko bude mať 14 stíhačiek.',
     'Minister obrany Robert Kaliňák (Smer-SD) obhajuje nákup tým, že je rozumnejšie kúpiť lietadlá teraz než riešiť problém o niekoľko rokov, a že na tridsaťročnú prevádzku je potrebný dostatočný počet strojov. Splácať sa má do roku 2030.'],
   sourceName:'STVR',source:'https://spravy.stvr.sk/2026/09/opozicia-kritizuje-nakup-styroch-novych-stihaciek-f-16-hovori-o-zbytocnom-luxuse-podla-ministra-kalinaka-ich-potrebujeme'},
  {id:'kuffa-september',published:'2026-09-10',category:'Vláda',title:'SNS presadzuje Kuffu, prezident má výhrady',
   summary:'Premiér podľa Denníka N sľúbil SNS, že návrh na odvolanie Tarabu pošle do 15. septembra. Strana presadzuje štátneho tajomníka Filipa Kuffu, ktorého prezident spochybnil.',
   detail:['Podľa Denníka N sľúbil premiér Robert Fico strane SNS, že návrh na odvolanie ministra životného prostredia Tomáša Tarabu pošle do prezidentského paláca najneskôr 15. septembra.',
     'SNS trvá na tom, aby ho nahradil súčasný štátny tajomník Filip Kuffa, a to napriek výhradám prezidenta Petra Pellegriniho, ktorý skôr uviedol, že na tento post existujú kvalitnejší kandidáti.',
     'Strana si pripravila aj obštrukcie v parlamente pre prípad, že by premiér jej požiadavky nesplnil. Predseda klubu Roman Michelko však povedal, že dôvod blokovať otvorenie schôdze nemajú.',
     'Taraba by podľa článku neskončil okamžite: má ešte zastupovať Slovensko na Valnom zhromaždení OSN v New Yorku od 22. do 28. septembra a čaká sa aj na termín v prezidentskom paláci.'],
   sourceName:'Denník N',source:'https://dennikn.sk/5553294/fico-do-utorka-odvola-tarabu-sns-sa-pripravila-aj-na-obstrukciu-prezidenta/'},
  {id:'v4-september',published:'2026-09-10',category:'Vláda',title:'V4 rokovala v Bratislave o rozpočte EÚ a energiách',
   summary:'Premiéri V4 sa na Bratislavskom hrade stretli aj s írskym premiérom. Fico zdôraznil poľnohospodársku politiku, ceny elektriny a koordináciu pred rokovaniami EÚ.',
   detail:['Premiéri krajín Vyšehradskej štvorky sa 10. septembra stretli na Bratislavskom hrade spoločne s írskym premiérom Micheálom Martinom. Témami boli rozpočet Európskej únie na ďalšie roky, spoločná poľnohospodárska politika, nové zdroje európskeho rozpočtu, ceny elektriny a pohonných látok, rozširovanie únie a migrácia.',
     'Robert Fico uviedol, že V4 má prinášať spoločné postoje k najaktuálnejším témam, a požiadal lídrov o koordináciu pred zasadnutím Európskej rady. Navrhol aj prípravu na úrovni šerpov pred takýmito stretnutiami.',
     'Odmietol, aby sa príjmy z emisných povoleniek používali ako nový zdroj rozpočtu EÚ. Írsky premiér avizoval návrh nového rozpočtu do niekoľkých týždňov a vyjadril podporu rozširovaniu únie.'],
   sourceName:'STVR / TASR',source:'https://spravy.stvr.sk/2026/09/premier-robert-fico-veri-ze-klucovou-temou-krajin-v4-bude-znizovanie-cien-elektriny/'},
  {id:'lex-para-september',published:'2026-09-10',category:'Parlament',title:'PS navrhuje obmedziť súbeh obhajoby a poradenstva vláde',
   summary:'Návrh má riešiť možný konflikt záujmov advokátov pôsobiacich ako vládni poradcovia. Predseda advokátskej komory ho odmieta ako protiústavný; zatiaľ ide o návrh zákona.',
   detail:['Progresívne Slovensko predložilo návrh zákona, ktorý má zabrániť tomu, aby advokát zároveň radil vláde či ministrom a obhajoval osoby obvinené z korupcie. V médiách sa označuje ako lex Para podľa advokáta Mareka Paru, poradcu premiéra.',
     'Poslankyňa Zuzana Mesterová argumentuje, že ide o konflikt záujmov, a porovnáva to s existujúcimi obmedzeniami, keď advokát nemôže byť zároveň prokurátorom, exekútorom ani sudcom.',
     'Predseda Slovenskej advokátskej komory Tomáš Kamenec návrh odmieta ako protiústavný a hovorí o porušení práva na obhajobu a spravodlivý proces. Marek Para ho označil za absurdný a kritizoval mrhanie prostriedkami.',
     'Zatiaľ ide o návrh zákona. PS pripúšťa úpravy v druhom čítaní a o podpore chce rokovať s ďalšími opozičnými stranami.'],
   sourceName:'STVR',source:'https://spravy.stvr.sk/2026/09/opozicia-navrhuje-lex-para-advokati-by-podla-ps-nemohli-radit-vlade-a-zaroven-obhajovat-obvinenych-z-korupcie/'},
  {id:'sns-blokovanie-09',published:'2026-09-09',category:'Parlament',title:'SNS nebude blokovať otvorenie septembrovej schôdze',
   summary:'Poslanecký klub oznámil, že rokovanie od 15. septembra blokovať nebude. Strana očakáva, že premiér v ten deň doručí návrh na odvolanie ministra životného prostredia.',
   detail:['Poslanecký klub SNS 9. septembra oznámil, že septembrovú schôdzu parlamentu blokovať nebude. Informáciu potvrdil štátny tajomník Filip Kuffa po rokovaní klubu.',
     'Strana zároveň uviedla, že očakáva, že premiér Robert Fico 15. septembra doručí prezidentovi písomný návrh na odvolanie ministra životného prostredia Tomáša Tarabu.',
     'Blokovanie schôdze bolo dovtedy jednou z možností, ktorými chcela SNS na premiéra zatlačiť.'],
   sourceName:'TN Live',source:'https://tnlive.sk/domace/clanok/1050189-sns-ustupuje-od-blokovania-parlamentu-ocakavaju-ze-premier-doruci-prezidentovi-navrh-na-odvolanie-ministra-tarabu'},
  {id:'border-september',published:'2026-09-09',category:'Vláda',title:'Cvičenie na českej hranici neznamená zavedenie kontrol',
   summary:'Slovenské a české bezpečnostné zložky preverovali postupy pri možnom obnovení hraničných kontrol. Minister Matúš Šutaj Eštok uviedol, že ich zavedenie v najbližšom období neočakáva.',
   detail:['Česká a slovenská polícia, armáda a colná správa absolvovali 9. septembra celodenné cvičenie pozdĺž 251 kilometrov spoločnej hranice. Zúčastnilo sa približne 750 príslušníkov a cvičenie sa skončilo 10. septembra ráno.',
     'Preverovali postupy pri možnom opätovnom zavedení hraničných kontrol: biometrickú registráciu, zásahy na zelenej hranici, postup pri zadržaní nelegálnych migrantov a kontroly na 17 bývalých cestných priechodoch. Za slovenskú stranu sa zapojili policajti z Trenčianskeho, Trnavského a Žilinského kraja.',
     'Minister vnútra Matúš Šutaj Eštok uviedol, že k ostrému zavedeniu kontrol na spoločnej hranici v najbližšom období nedôjde a že cvičenia majú odhaliť nedostatky skôr, než by k reálnemu nasadeniu došlo. Český minister Lubomír Metnar hovoril o preverovaní pripravenosti na migračný tlak.'],
   sourceName:'STVR / TASR',source:'https://spravy.stvr.sk/spravy-po-minute/k-zavedeniu-kontrol-na-hranici-s-ceskom-v-najblizsom-obdobi-nedojde-potvrdil-minister-sutaj-estok/'}
];

/**
 * „Posledných 7 dní“ je pohyblivé okno vrátane dneška, nie kalendárny týždeň:
 * v pondelok by kalendárny týždeň ukázal iba dnešok a prehľad by pôsobil prázdno.
 * Budúce dátumy sa nezobrazujú nikdy, ani v celom výbere.
 */
export function filterNews(items:PoliticalNews[],today:string,period:string,category:string){
  const from=new Date(new Date(today+'T12:00:00Z').getTime()-6*86400000).toISOString().slice(0,10);
  return items.filter(n=>n.published<=today&&(category==='all'||n.category===category)&&(period==='all'||(period==='today'?n.published===today:n.published>=from))).sort((a,b)=>b.published.localeCompare(a.published)||a.id.localeCompare(b.id));
}

export const newsById=(id:string|null)=>id?politicalNews.find(n=>n.id===id)??null:null;
