export type ProgrammeStatus = "archive-2023" | "current-initiative" | "current-undated" | "draft-2027" | "approved-2027";
export type Programme = {
  partyId:string; title:string; author:string; year:number|null;
  format:"PDF"|"Web"; url:string; contextUrl?:string;
  description:string; note:string; topics:string[]; verified:string;
  status:ProgrammeStatus; published?:string;
};

export const statusLabel:Record<ProgrammeStatus,string> = {
  "archive-2023":"Archív · voľby 2023",
  "current-initiative":"Aktuálny návrh / iniciatíva",
  "current-undated":"Aktuálna stránka · ročník neuvedený",
  "draft-2027":"Návrh programu 2027",
  "approved-2027":"Schválený program 2027"
};

export const programmes:Programme[] = [
  {partyId:"ps",title:"TRESK",author:"Progresívne Slovensko",year:null,status:"current-initiative",published:"2025-09-04",format:"PDF",url:"https://progresivne.sk/wp-content/uploads/2025/09/PS_TRESK_BROZURA.pdf",contextUrl:"https://progresivne.sk/tresk-v-siedmich-oblastiach-prinasa-novy-ekonomicky-model-ktory-dlhodobo-zlepsi-zivotnu-uroven-na-slovensku/",description:"Ekonomický plán so siedmimi prepojenými oblasťami: investície, podnikateľské prostredie, ľudský kapitál, verejné služby a udržateľnosť.",note:"PS dokument predstavilo ako plán reštartu ekonomiky a podklad pre rokovania o povolebnej spolupráci. Nie je označený ako úplný ani schválený volebný program pre voľby 2027.",topics:["Ekonomika a dane","Zdravotníctvo","Vzdelávanie","Bývanie"],verified:"2026-09-12"},
  {partyId:"dem",title:"Programové piliere našej politiky",author:"Demokrati",year:null,status:"current-initiative",format:"Web",url:"https://www.smedemokrati.sk/programove-piliere-nasej-politiky/",description:"Päť pilierov pripravovaného programu: zdravé, vzdelané, bezpečné, angažované a sociálne Slovensko.",note:"Strana na stránke výslovne uvádza, že na volebnom programe pre nasledujúce obdobie pracuje. Piliere preto evidujeme ako aktuálny rozpracovaný rámec, nie ako hotový program 2027.",topics:["Ekonomika a dane","Zdravotníctvo","Vzdelávanie","Zahraničná politika"],verified:"2026-09-12"},
  {partyId:"kdh",title:"Päť programových priorít",author:"KDH",year:null,status:"current-undated",format:"Web",url:"https://kdh.sk/program/",description:"Oficiálna programová stránka uvádza opatrenia pre životnú úroveň, zdravotníctvo, rodiny a vzdelávanie.",note:"Stránka hovorí o nasledujúcom volebnom období, ale neuvádza volebný ročník. Bez ďalšieho potvrdenia ju neoznačujeme ako schválený program pre voľby 2027.",topics:["Ekonomika a dane","Zdravotníctvo","Vzdelávanie","Rodiny"],verified:"2026-09-12"},
  {partyId:"hlas",title:"Rodinný balík a pracovné návrhy",author:"HLAS – sociálna demokracia",year:null,status:"current-initiative",published:"2026-06-30",format:"Web",url:"https://strana-hlas.sk/aktuality/michaela-eliasova/prinasame-opatrenia-na-zvysenie-kocikovneho-a-na-zrusenie-dane-z-prijmu-pre-viacnasobne-mamicky/",contextUrl:"https://strana-hlas.sk/nase-navrhy/",description:"Aktuálne návrhy strany vrátane zvýšenia príspevku pri narodení dieťaťa, daňového oslobodenia vybraných rodičov a rodinnej karty.",note:"Ide o konkrétny balík predstavený v roku 2026, nie o úplný volebný program 2027. Ďalšie návrhy eviduje živá sekcia strany.",topics:["Ekonomika a dane","Rodiny"],verified:"2026-09-12"},
  {partyId:"rep",title:"Program na obnovu Slovenska",author:"REPUBLIKA",year:null,status:"current-undated",format:"Web",url:"https://www.hnutie-republika.sk/program/",contextUrl:"https://www.hnutie-republika.sk/predvolebne-noviny-2023/",description:"Živá programová stránka rozdeľuje návrhy podľa oblastí štátu, hospodárstva, zdravotníctva, školstva a zahraničnej politiky.",note:"Na adresu odkazovali aj predvolebné noviny 2023, no dátum dnešného znenia nie je doložený. Nepriraďujeme jej volebný ročník ani status programu 2027.",topics:["Ekonomika a dane","Zdravotníctvo","Vzdelávanie","Spravodlivosť","Zahraničná politika"],verified:"2026-09-12"},
  {partyId:"dem",title:"Plán pomoci ľuďom",author:"Demokrati",year:2023,status:"archive-2023",published:"2023-09-01",format:"PDF",url:"https://www.smedemokrati.sk/wp-content/themes/demokrati_theme/assets/Program_demokratov.pdf",description:"Program člení návrhy do oblastí bezpečnosti, spravodlivosti, zdravia, vzdelávania, sociálnej politiky a hospodárstva.",note:"September 2023 je uvedený na titulnej strane. Ide o historický volebný dokument, nie o dnešný program.",topics:["Ekonomika a dane","Zdravotníctvo","Vzdelávanie","Spravodlivosť","Zahraničná politika"],verified:"2026-09-10"},
  {partyId:"slovensko",title:"Ty rozhodneš · program 2023",author:"OĽANO a PRIATELIA (2023)",year:2023,status:"archive-2023",format:"PDF",url:"https://www.obycajniludia.sk/wp-content/uploads/2023/09/olano_program_2023.pdf",description:"Dokument uvádza priority v boji proti korupcii, spravodlivosti, podpore rodín, školstve a zdravotníctve.",note:"Historický dokument z roku 2023 zachovávame pod pôvodným označením autora. Nie je to nový program Hnutia SLOVENSKO.",topics:["Ekonomika a dane","Zdravotníctvo","Vzdelávanie","Spravodlivosť","Zahraničná politika"],verified:"2026-09-10"},
  {partyId:"kdh",title:"Rozumnejšie. Zodpovednejšie. Lepšie.",author:"KDH",year:2023,status:"archive-2023",format:"PDF",url:"https://kdh.sk/wp-content/uploads/2023/07/KDH-program-2023-web.pdf",description:"Program obsahuje desať oblastí vrátane ekonomiky, energetiky, školstva, zdravotníctva, sociálnej politiky a správy štátu.",note:"Historický volebný program KDH 2023; rok je uvedený v dokumente.",topics:["Ekonomika a dane","Zdravotníctvo","Vzdelávanie","Spravodlivosť","Zahraničná politika"],verified:"2026-09-10"},
  {partyId:"ps",title:"Plán pre budúcnosť",author:"Progresívne Slovensko",year:2023,status:"archive-2023",published:"2023-09-02",format:"Web",url:"https://progresivne.sk/program/",contextUrl:"https://progresivne.sk/progresivne-slovensko-predstavilo-volebny-program-s-nazvom-plan-pre-buducnost/",description:"Volebný program 2023 ponúkal tematické kapitoly k ekonomike, zdravotníctvu, vzdelávaniu, bývaniu a ďalším oblastiam.",note:"Predstavený 2. 9. 2023. Odkaz vedie na živú stránku, preto jej dnešné znenie nemusí byť nemennou archívnou kópiou.",topics:["Ekonomika a dane","Zdravotníctvo","Vzdelávanie","Spravodlivosť","Zahraničná politika"],verified:"2026-09-10"},
  {partyId:"smer",title:"Volebný program · parlamentné voľby 2023",author:"SMER – slovenská sociálna demokracia",year:2023,status:"archive-2023",published:"2023-04-03",format:"Web",url:"https://www.strana-smer.sk/aktuality/blogy/post/volby-2023",description:"Dokument zoskupuje zámery v zahraničnej politike a sociálnej oblasti vrátane dôchodkov a podpory domácností.",note:"Historický dokument z roku 2023. Označenie obdobia 2023 – 2027 z neho nerobí program pre voľby 2027.",topics:["Ekonomika a dane","Zahraničná politika"],verified:"2026-09-10"},
  {partyId:"hlas",title:"Rezortný program HLAS",author:"HLAS – sociálna demokracia",year:2023,status:"archive-2023",format:"PDF",url:"https://strana-hlas.sk/wp-content/uploads/2023/09/Rezortny-program-HLAS.pdf",description:"Historický rezortný dokument pre voľby 2023 pokrýva ekonomiku, sociálnu politiku, zdravotníctvo, školstvo a zahraničnú politiku.",note:"Súbor bol zverejnený v septembri 2023. Evidujeme ho výhradne v archíve volieb 2023.",topics:["Ekonomika a dane","Zdravotníctvo","Vzdelávanie","Zahraničná politika","Rodiny"],verified:"2026-09-12"}
];

export const programmeTopics=["Ekonomika a dane","Zdravotníctvo","Vzdelávanie","Zahraničná politika","Spravodlivosť","Rodiny","Bývanie"];

export type Position = {partyId:string; topic:string; status:ProgrammeStatus; bullets:string[]; source:string; sourceTitle:string; asOf:string};
export const positions:Position[] = [
  {partyId:"ps",topic:"Ekonomika a dane",status:"current-initiative",source:"https://progresivne.sk/tresk-v-siedmich-oblastiach-prinasa-novy-ekonomicky-model-ktory-dlhodobo-zlepsi-zivotnu-uroven-na-slovensku/",sourceTitle:"PS · TRESK",asOf:"2025-09-04",bullets:["Znížiť dane a odvody z práce.","Zaviesť ByroKAT na zjednodušenie štátu a podnikania.","Pripraviť národný investičný plán a profesionálnejšie riadiť eurofondy."]},
  {partyId:"ps",topic:"Zdravotníctvo",status:"current-initiative",source:"https://progresivne.sk/wp-content/uploads/2025/09/PS_TRESK_BROZURA.pdf",sourceTitle:"PS · TRESK",asOf:"2025-09-04",bullets:["Zvýšiť efektívnosť zdravotníctva.","Posilniť prevenciu a dlhodobú starostlivosť.","Vnímať funkčné nemocnice ako súčasť nového ekonomického modelu."]},
  {partyId:"ps",topic:"Vzdelávanie",status:"current-initiative",source:"https://progresivne.sk/wp-content/uploads/2025/09/PS_TRESK_BROZURA.pdf",sourceTitle:"PS · TRESK",asOf:"2025-09-04",bullets:["Rozšíriť dostupnosť starostlivosti a vzdelávania pre deti do troch rokov.","Orientovať vzdelávanie viac na zručnosti.","Podporiť rekvalifikáciu a ďalšie vzdelávanie dospelých."]},
  {partyId:"kdh",topic:"Ekonomika a dane",status:"current-initiative",source:"https://kdh.sk/ekonomika-je-pre-kdh-prioritou-rastislav-kratky-bol-zvoleny-za-podpredsedu-hospodarskeho-vyboru/",sourceTitle:"KDH · ekonomické priority",asOf:"2026-05-22",bullets:["Presadzovať návrat k rovnej dani.","Znížiť odvodové zaťaženie práce."]},
  {partyId:"kdh",topic:"Zdravotníctvo",status:"current-undated",source:"https://kdh.sk/program/",sourceTitle:"KDH · programová stránka",asOf:"2026-09-12",bullets:["Zaviesť transparentné čakacie lehoty na operácie.","Zvýšiť počet začínajúcich sestier najmenej o 10 % a dať im štartovací príspevok.","Zabezpečiť ambulantné centrá v oblastiach s nedostatkom lekárov."]},
  {partyId:"kdh",topic:"Vzdelávanie",status:"current-undated",source:"https://kdh.sk/program/",sourceTitle:"KDH · programová stránka",asOf:"2026-09-12",bullets:["Pripraviť deti na zručnosti potrebné v 21. storočí.","Viac finančne motivovať duálne vzdelávanie."]},
  {partyId:"dem",topic:"Ekonomika a dane",status:"current-initiative",source:"https://www.smedemokrati.sk/programove-piliere-nasej-politiky/",sourceTitle:"Demokrati · programové piliere",asOf:"2026-09-12",bullets:["Znížiť daňové zaťaženie práce.","Nastaviť udržateľný ekonomický model pre dobiehanie výkonnejších štátov EÚ.","Reorganizovať štát na princípe subsidiarity a ekonomickej efektivity."]},
  {partyId:"dem",topic:"Zdravotníctvo",status:"current-initiative",source:"https://www.smedemokrati.sk/programove-piliere-nasej-politiky/",sourceTitle:"Demokrati · programové piliere",asOf:"2026-09-12",bullets:["Modernizovať zdravotnícku infraštruktúru a rozšíriť sieť ambulancií.","Motivovať mladých lekárov a lekárky pracovať na Slovensku.","Posilniť prevenciu a efektívne využitie zdrojov."]},
  {partyId:"dem",topic:"Vzdelávanie",status:"current-initiative",source:"https://www.smedemokrati.sk/programove-piliere-nasej-politiky/",sourceTitle:"Demokrati · programové piliere",asOf:"2026-09-12",bullets:["Postaviť politiku vzdelávania na kvalitných a nezávislých učiteľoch.","Rozvíjať kritické myslenie, samostatnosť a podnikavosť.","Prepojiť konkurencieschopné vysoké školy s inovatívnymi firmami."]},
  {partyId:"dem",topic:"Zahraničná politika",status:"current-initiative",source:"https://www.smedemokrati.sk/programove-piliere-nasej-politiky/",sourceTitle:"Demokrati · programové piliere",asOf:"2026-09-12",bullets:["Zachovať pevné ukotvenie Slovenska v EÚ a NATO.","Podporovať právo Ukrajiny a ďalších demokratických štátov uchádzať sa o členstvo.","Dodržiavať záväzok výdavkov na obranu najmenej 2 % HDP."]},
  {partyId:"hlas",topic:"Rodiny",status:"current-initiative",source:"https://strana-hlas.sk/aktuality/michaela-eliasova/prinasame-opatrenia-na-zvysenie-kocikovneho-a-na-zrusenie-dane-z-prijmu-pre-viacnasobne-mamicky/",sourceTitle:"HLAS · rodinný balík",asOf:"2026-06-30",bullets:["Zvýšiť príspevok pri narodení prvého dieťaťa na 1 000 eur.","Oslobodiť od dane z príjmu pracujúcich rodičov so štyrmi a viac deťmi podľa podmienok návrhu.","Zaviesť rodinnú kartu so zľavami na tovary a služby pre rodiny s deťmi."]}
];
