export type BuildingId = "house" | "school" | "library" | "clinic" | "park" | "market" | "workshop" | "garden" | "culture" | "town-hall" | "plaza" | "station";
export type DecorationId = "bench" | "flower-bed" | "linden" | "fountain" | "book-kiosk" | "pergola" | "clock" | "bandstand" | "sculpture" | "observatory" | "glasshouse" | "ceremonial-gate";
export type ItemId = BuildingId | DecorationId;
export type Branch = "museum" | "market-hall" | "community-hall";
export type Point = { x: number; y: number };
export type Placed = Point & { instanceId: string; id: ItemId; fixed?: boolean };
export type Pending = { sequence: number; rarity: Rarity; cards: [DecorationId, DecorationId, DecorationId] };
export type Rarity = "common" | "uncommon" | "rare" | "epic";
export type RepublicState = {
  version: 1; revision: number; name: string; coins: number; materials: number; createdDay: string; lastDay: string;
  charges: number; claimSequence: number; pending: Pending | null; unlocked: DecorationId[]; placed: Placed[]; inventory: Placed[];
  roads: Point[]; completed: string[]; branch: Branch | null; finalReward: boolean; claimedTasks: string[]; lastProjectDay: string | null;
};
export type Result = { ok: true; state: RepublicState; message: string } | { ok: false; message: string };
export const MAP_SIZE = 6;
export const fixed: Placed[] = [
  { instanceId: "plaza", id: "plaza", x: 2, y: 2, fixed: true }, { instanceId: "hall", id: "town-hall", x: 2, y: 1, fixed: true },
  { instanceId: "station", id: "station", x: 5, y: 1, fixed: true },
];
const startPlaced: Placed[] = [
  ...fixed, { instanceId: "school-1", id: "school", x: 1, y: 1 }, { instanceId: "house-1", id: "house", x: 0, y: 1 },
  { instanceId: "house-2", id: "house", x: 3, y: 1 }, { instanceId: "house-3", id: "house", x: 4, y: 3 },
];
const startRoads = [[0,2],[1,2],[3,2],[4,2],[5,2]].map(([x,y])=>({x,y}));
export const catalog: Record<ItemId, { name: string; coins: number; materials: number; kind: "building" | "decoration"; icon: string }> = {
  house:{name:"Dom",coins:4,materials:2,kind:"building",icon:"house"}, school:{name:"Škola",coins:7,materials:4,kind:"building",icon:"school"}, library:{name:"Knižnica",coins:6,materials:3,kind:"building",icon:"library"}, clinic:{name:"Ambulancia",coins:7,materials:4,kind:"building",icon:"clinic"}, park:{name:"Park",coins:3,materials:2,kind:"building",icon:"park"}, market:{name:"Tržnica",coins:6,materials:3,kind:"building",icon:"market"}, workshop:{name:"Dielňa",coins:5,materials:3,kind:"building",icon:"workshop"}, garden:{name:"Záhrada",coins:3,materials:2,kind:"building",icon:"garden"}, culture:{name:"Kultúrny dom",coins:6,materials:3,kind:"building",icon:"culture"}, "town-hall":{name:"Radnica",coins:0,materials:0,kind:"building",icon:"hall"}, plaza:{name:"Námestie",coins:0,materials:0,kind:"building",icon:"plaza"}, station:{name:"Stará stanica",coins:0,materials:0,kind:"building",icon:"station"},
  bench:{name:"Lavička",coins:0,materials:0,kind:"decoration",icon:"bench"}, "flower-bed":{name:"Kvetinový záhon",coins:0,materials:0,kind:"decoration",icon:"flower"}, linden:{name:"Lipa",coins:0,materials:0,kind:"decoration",icon:"tree"}, fountain:{name:"Fontána",coins:0,materials:0,kind:"decoration",icon:"fountain"}, "book-kiosk":{name:"Knižný kiosk",coins:0,materials:0,kind:"decoration",icon:"kiosk"}, pergola:{name:"Pergola",coins:0,materials:0,kind:"decoration",icon:"pergola"}, clock:{name:"Vežové hodiny",coins:0,materials:0,kind:"decoration",icon:"clock"}, bandstand:{name:"Hudobný pavilón",coins:0,materials:0,kind:"decoration",icon:"bandstand"}, sculpture:{name:"Socha",coins:0,materials:0,kind:"decoration",icon:"sculpture"}, observatory:{name:"Hvezdáreň",coins:0,materials:0,kind:"decoration",icon:"observatory"}, glasshouse:{name:"Skleník",coins:0,materials:0,kind:"decoration",icon:"glasshouse"}, "ceremonial-gate":{name:"Slávnostná brána",coins:0,materials:0,kind:"decoration",icon:"gate"},
};
const pools: Record<Rarity, [DecorationId, DecorationId, DecorationId]> = { common:["bench","flower-bed","linden"], uncommon:["fountain","book-kiosk","pergola"], rare:["clock","bandstand","sculpture"], epic:["observatory","glasshouse","ceremonial-gate"] };
const days = (day:string) => Math.floor(Date.UTC(+day.slice(0,4),+day.slice(5,7)-1,+day.slice(8,10))/86400000);
const k = (p:Point) => `${p.x},${p.y}`;
const dist = (a:Point,b:Point) => Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
const inMap = (p:Point) => Number.isInteger(p.x)&&Number.isInteger(p.y)&&p.x>=0&&p.y>=0&&p.x<MAP_SIZE&&p.y<MAP_SIZE;
const same = (a:Point,b:Point) => a.x===b.x&&a.y===b.y;
const clone = (s:RepublicState):RepublicState => ({...s,placed:s.placed.map(x=>({...x})),inventory:s.inventory.map(x=>({...x})),roads:s.roads.map(x=>({...x})),unlocked:[...s.unlocked],completed:[...s.completed],claimedTasks:[...s.claimedTasks],pending:s.pending?{...s.pending,cards:[...s.pending.cards] as Pending["cards"]}:null});
export function slovakDay(now = new Date()) {
  const parts = new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Bratislava",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(now);
  const get = (type:string) => parts.find(part=>part.type===type)?.value ?? "";
  return `${get("year")}-${get("month")}-${get("day")}`;
}
export function createTown(day = slovakDay()): RepublicState { return {version:1,revision:0,name:"Lipová štvrť",coins:12,materials:8,createdDay:day,lastDay:day,charges:1,claimSequence:0,pending:null,unlocked:[],placed:startPlaced.map(x=>({...x})),inventory:[],roads:startRoads.map(x=>({...x})),completed:[],branch:null,finalReward:false,claimedTasks:[],lastProjectDay:null}; }
export function network(state:RepublicState) { const root={x:2,y:2}; const all=[root,...state.roads]; const found=new Set([k(root)]); const queue=[root]; while(queue.length){const p=queue.shift()!; for(const n of all)if(!found.has(k(n))&&dist(p,n)===1){found.add(k(n));queue.push(n);}} return all.filter(p=>found.has(k(p))); }
export function connected(state:RepublicState,p:Point){return network(state).some(n=>dist(n,p)===1);}
export function items(state:RepublicState,id:ItemId){return state.placed.filter(p=>p.id===id);}
export function paired(state:RepublicState,a:ItemId,b:ItemId){return items(state,a).some(x=>connected(state,x)&&items(state,b).some(y=>connected(state,y)&&dist(x,y)<=2));}
export function coveredHomes(state:RepublicState,id: "clinic"|"park"|"garden"){return new Set(items(state,id).filter(x=>connected(state,x)).flatMap(service=>items(state,"house").filter(home=>connected(state,home)&&dist(service,home)<=2).map(h=>h.instanceId))).size;}
export function combos(state:RepublicState){return {school:paired(state,"school","library"),craft:paired(state,"school","workshop"),centre:items(state,"market").some(x=>connected(state,x)&&dist(x,{x:2,y:2})<=2)};}
export const steps = [
  {id:"school-yard",name:"Školský dvor",speaker:"Eva",text:"Po vyučovaní nám chýba miesto vonku. Nájdeme pri škole kúsok zelene?",done:(s:RepublicState)=>paired(s,"school","park")||paired(s,"school","garden"),reward:[2,1] as const},
  {id:"books",name:"Cesta za knihami",speaker:"Eva",text:"Máme dvor. Teraz by sme radi chodili za knihami pešo.",done:(s:RepublicState)=>paired(s,"school","library"),reward:[2,1] as const},
  {id:"care",name:"Blízka ambulancia",speaker:"Nina",text:"Ambulancia by mala byť blízko domov. Skúsme ju umiestniť tak, aby slúžila aspoň dvom.",done:(s:RepublicState)=>coveredHomes(s,"clinic")>=2,reward:[2,1] as const},
  {id:"square",name:"Malý trh",speaker:"Nina",text:"Na námestí môže byť rušno aj bez veľkého festivalu. Začnime malým trhom.",done:(s:RepublicState)=>combos(s).centre,reward:[2,1] as const},
  {id:"discovery",name:"Stará hala",speaker:"Milan",text:"V stanici sme našli starú halu. Čo by v nej malo vzniknúť?",done:(s:RepublicState)=>!!s.branch,reward:[0,0] as const},
  {id:"preparation",name:"Pripraviť halu",speaker:"Milan",text:"Pripravme halu aj jej okolie. Ľudia sa sem musia vedieť dostať.",done:(s:RepublicState)=>!!s.branch&&items(s,s.branch==="museum"?"library":s.branch==="market-hall"?"market":"park").some(x=>connected(s,x)&&dist(x,{x:5,y:1})<=2),reward:[0,0] as const},
  {id:"opening",name:"Otvoriť dvere",speaker:"Nina",text:"Dvere sa môžu otvoriť. Dnes patrí stanica celej štvrti.",done:(s:RepublicState)=>connected(s,{x:5,y:1})&&items(s,"house").filter(x=>connected(s,x)).length>=3&&Object.values(combos(s)).some(Boolean),reward:[0,0] as const},
];
export function currentStep(state:RepublicState){return steps.find(s=>!state.completed.includes(s.id))??null;}
function revision(s:RepublicState){s.revision++;return s;}
function rarity(sequence:number):Rarity { const n=(sequence*37+17)%100;return n<60?"common":n<85?"uncommon":n<97?"rare":"epic"; }
export function accrue(state:RepublicState,today:string):RepublicState { const s=clone(state); const delta=Math.max(0,days(today)-days(s.lastDay)); if(delta){s.charges=Math.min(3,s.charges+delta);s.lastDay=today;} return s; }
export function place(state:RepublicState, id:ItemId, target:Point):Result { if(!inMap(target)) return {ok:false,message:"Toto miesto je mimo štvrte."}; const s=clone(state); if(s.placed.some(p=>same(p,target))||s.roads.some(p=>same(p,target)))return{ok:false,message:"Toto políčko už niečo zaberá."}; if(!(id in catalog)||id==="town-hall"||id==="plaza"||id==="station")return{ok:false,message:"Tento orientačný bod sa nedá stavať."}; const inv=s.inventory.find(p=>p.id===id); const d=catalog[id]; if(d.kind==="decoration"&&!s.unlocked.includes(id as DecorationId))return{ok:false,message:"Túto ozdobu najprv odomkni zo zásielky."}; if(!inv && (s.coins<d.coins||s.materials<d.materials))return{ok:false,message:"Na túto stavbu zatiaľ nemáš dosť zdrojov."}; if(inv){s.inventory=s.inventory.filter(p=>p.instanceId!==inv.instanceId);s.placed.push({...inv,...target});}else{s.coins-=d.coins;s.materials-=d.materials;s.placed.push({instanceId:`${id}-${s.revision+1}-${s.placed.length}`,...target,id});}return{ok:true,state:revision(s),message:inv?`${d.name} je späť v štvrti.`:`Postavené: ${d.name}.`}; }
export function store(state:RepublicState,instanceId:string):Result { const s=clone(state); const thing=s.placed.find(p=>p.instanceId===instanceId);if(!thing)return{ok:false,message:"Túto stavbu sme nenašli."};if(thing.fixed)return{ok:false,message:"Tento orientačný bod sa nedá presunúť."};s.placed=s.placed.filter(p=>p.instanceId!==instanceId);s.inventory.push(thing);return{ok:true,state:revision(s),message:`${catalog[thing.id].name} je v zásobe.`}; }
export function toggleRoad(state:RepublicState,target:Point):Result { if(!inMap(target))return{ok:false,message:"Cesta môže byť iba v mape."};const s=clone(state);if(s.placed.some(p=>same(p,target)))return{ok:false,message:"Pod stavbou cestu nevieš viesť."};const i=s.roads.findIndex(p=>same(p,target));if(i>=0)s.roads.splice(i,1);else s.roads.push(target);return{ok:true,state:revision(s),message:i>=0?"Cesta odstránená.":"Cesta položená."};}
export function openParcel(state:RepublicState):Result { const s=clone(state);if(s.pending)return{ok:false,message:"Najprv si vyber jednu z otvorených vecí."};if(!s.charges)return{ok:false,message:"Nová zásielka príde zajtra. Môžu sa nahromadiť najviac tri."};const r=rarity(s.claimSequence);s.charges--;s.pending={sequence:s.claimSequence++,rarity:r,cards:pools[r]};return{ok:true,state:revision(s),message:"Zásielka je pripravená."};}
export function claimParcel(state:RepublicState,id:DecorationId):Result { const s=clone(state);if(!s.pending||!s.pending.cards.includes(id))return{ok:false,message:"Vyber jednu z ponúknutých dekorácií."};const duplicate=s.unlocked.includes(id);if(duplicate)s.materials=Math.min(999,s.materials+2);else{s.coins=Math.min(999,s.coins+8);s.materials=Math.min(999,s.materials+4);s.unlocked.push(id);}s.pending=null;return{ok:true,state:revision(s),message:duplicate?"Duplikát sa zmenil na +2 materiály.":`${catalog[id].name} pribudla do zbierky. +8 mincí, +4 materiály.`};}
export function chooseBranch(state:RepublicState,branch:Branch):Result {const s=clone(state);const step=currentStep(s);if(!step||step.id!=="discovery")return{ok:false,message:"Halu teraz ešte nie je možné rozhodnúť."};if(s.lastProjectDay===s.lastDay)return{ok:false,message:"Dnešný krok projektu už máš za sebou. Pokračovanie príde zajtra."};s.branch=branch;s.completed.push(step.id);s.lastProjectDay=s.lastDay;return{ok:true,state:revision(s),message:"Budúcnosť starej haly je rozhodnutá. Pokračovanie príde zajtra."};}
export function completeStep(state:RepublicState):Result {const s=clone(state);const step=currentStep(s);if(!step)return{ok:false,message:"Kapitola je hotová."};if(s.lastProjectDay===s.lastDay)return{ok:false,message:"Dnešný krok projektu už máš za sebou. Pokračovanie príde zajtra."};if(step.id==="discovery")return{ok:false,message:"Najprv vyber podobu starej haly."};if(!step.done(s))return{ok:false,message:"Ešte chýba prepojenie zobrazené v cieli."};const cost=step.id==="preparation"?[6,4] as const:step.id==="opening"?[8,4] as const:[0,0] as const;if(s.coins<cost[0]||s.materials<cost[1])return{ok:false,message:"Na tento krok chýbajú zdroje."};s.coins-=cost[0];s.materials-=cost[1];s.coins+=step.reward[0];s.materials+=step.reward[1];s.completed.push(step.id);s.lastProjectDay=s.lastDay;return{ok:true,state:revision(s),message:step.id==="opening"?"Stanica znova žije.":"Krok projektu je hotový. Pokračovanie príde zajtra."};}
export function claimFinalDecoration(state:RepublicState,id:DecorationId):Result {const s=clone(state);if(!s.completed.includes("opening"))return{ok:false,message:"Najprv dokonči kapitolu."};if(s.finalReward)return{ok:false,message:"Finálnu dekoráciu si už vybral."};if(!(id in catalog)||catalog[id].kind!=="decoration")return{ok:false,message:"Vyber dekoráciu zo zbierky."};if(!s.unlocked.includes(id))s.unlocked.push(id);s.finalReward=true;return{ok:true,state:revision(s),message:`${catalog[id].name} je tvoja finálna dekorácia.`};}
export function claimTask(state:RepublicState, task:"school-link"|"green-home"|"three-homes"|"care-two"|"market-square"|"school-pair"|"craft-pair"|"green-two"):Result { const s=clone(state);const claimId=`${s.lastDay}:${task}`;if(s.claimedTasks.includes(claimId)||s.claimedTasks.includes(task))return{ok:false,message:"Túto objednávku si už vyzdvihol."};const c=combos(s);const passed={"school-link":items(s,"school").some(x=>connected(s,x)),"green-home":coveredHomes(s,"park")+coveredHomes(s,"garden")>=1,"three-homes":items(s,"house").filter(x=>connected(s,x)).length>=3,"care-two":coveredHomes(s,"clinic")>=2,"market-square":c.centre,"school-pair":c.school,"craft-pair":c.craft,"green-two":coveredHomes(s,"park")+coveredHomes(s,"garden")>=2}[task];if(!passed)return{ok:false,message:"Táto objednávka ešte nie je splnená."};s.claimedTasks.push(claimId);s.coins+=2;s.materials+=1;return{ok:true,state:revision(s),message:"Objednávka vybavená. +2 mince, +1 materiál."};}
export function readSave(value:unknown,day=slovakDay()):RepublicState|null { if(!value||typeof value!=="object")return null;const s=value as Partial<RepublicState>;if(s.version!==1||!Array.isArray(s.placed)||!Array.isArray(s.roads)||!Array.isArray(s.inventory)||typeof s.coins!=="number"||typeof s.materials!=="number"||typeof s.lastDay!=="string")return null;try{return accrue({...s,lastProjectDay:typeof s.lastProjectDay==="string"?s.lastProjectDay:null} as RepublicState,day);}catch{return null;} }
